### ISSUE TITLE
Specification : mitre attack sub-techniques and tags : T1021.002

### ISSUE THREAD

**Issue by 59e5aaf4** [Neo23x0/sigma#1088]
How should the new sub-techniques identifiers be included in tags ?

The Sigma specification only mentions `attack.t1234`, should we use `attack.t1234.001`? should we use two tags, `attack.t1234` and `attack.t1234.001` ?

* https://attack.mitre.org/techniques/T1021/002/

Thanks, best regards, etc,

**Comment by yugoslavskiy** [comment]
Hello @59e5aaf4 ! 

> attack.t1234.001

This is the correct one (: 
Most of the rules have updated tags with this notation for the sub-techniques. 

> should we use two tags [...]?

We should use the most precise tag when possible. 
So if a rule could be directly mapped to a sub-technique, we should use a sub-technique tag. 

Let me know if it helps.
