### ISSUE TITLE
[Feature Request] Graylog Support

### ISSUE THREAD

**Issue by ion-storm** [Neo23x0/sigma#11]
I would love to see this support Graylog and their rest api:
http://docs.graylog.org/en/2.2/pages/configuration/rest_api.html

**Comment by thomaspatzke** [comment]
Currently, only file-based outputs are planned in sigmac. But there is a possibility that you can use the es-qs backend for Graylog, as it uses the Lucene syntax and is based on Elasticsearch. [See also this enhancement request](https://github.com/Neo23x0/sigma/issues/5).

**Comment by jothoma1** [comment]
Interested too for this enhancement !

**Comment by ion-storm** [comment]
could possibly leverage their pipelines as well

**Comment by lennartkoopmann** [comment]
Graylog founder here. This is indeed very interesting and I'm investigating.

**Comment by thomaspatzke** [comment]
Paul Dutot contributed a Graylog backend and I've merged it. Hasn't tested it myself, so testing would be much appreciated!
