### ISSUE TITLE
LONG_DESCRIPTION.md and LGPL license not included in sdist

### ISSUE THREAD

**Issue by joachimmetz** [Neo23x0/sigma#1180]
The sdist package provided on https://pypi.org/project/sigmatools/#files does not provide LONG_DESCRIPTION.md

This file appears to be required by setup.py https://github.com/Neo23x0/sigma/blob/master/tools/setup.py#L12. 

Consider adding a MANIFEST.in file to ensure LONG_DESCRIPTION.md is included in the sdist package e.g.

tools\MANIFEST.in
```
include LONG_DESCRIPTION.md
```

**Comment by joachimmetz** [comment]
You likely want to add a copy of the LGPL license file in the same way, since you are "distributing" the package on PyPI

**Comment by jaegeral** [comment]
Friendly bump here

**Comment by thomaspatzke** [comment]
Fixed, release pending.

**Comment by joachimmetz** [comment]
@thomaspatzke Please reopen I do not see a license file in https://pypi.org/project/sigmatools/#files sigmatools-0.19.tar.gz

**Comment by joachimmetz** [comment]
This prevent us from using sigmatools in Docker builds that use pip

**Comment by joachimmetz** [comment]
You need to add the license file to Manifest.in

**Comment by thomaspatzke** [comment]
Hope it's fixed properly now 😊

**Comment by joachimmetz** [comment]
thx this looks better, ths sigmatools-0.19.1 sdist on PyPI now contains LICENSE.LGPL.txt
