### ISSUE TITLE
Predefined tag "c2" in Wiki seems to have fallen out of use in comparison to "command_and_control"

### ISSUE THREAD

**Issue by DiogoBraz** [Neo23x0/sigma#1303]
It seems that the majority of the community uses "attack.command_and_control" instead of the proposed predifined tag "c2". 
I would suggest that changing the wiki to follow the community practice is probably the easier solution. What do you think?

Keep up the good work!

**Comment by Neo23x0** [comment]
Yes, correct.

**Comment by Neo23x0** [comment]
Fixed
