### ISSUE TITLE
fieldlist fails for multiple rules

### ISSUE THREAD

**Issue by traut** [Neo23x0/sigma#1351]
While trying to get the list of fieldnames used in the rules (as advised in the documetation), I've encountered the issue that multiple rules do not support it and the command fails:
```
$ git checkout devel
Switched to branch 'devel'
Your branch is up to date with 'origin/devel'.

$ git log -n 1
commit c6fc9de1442feeaef7fa6a21d7eed6b79f1f6e11 (HEAD -> devel, origin/devel)
Author: Florian Roth <venom14@gmail.com>
Date:   Thu Nov 26 09:54:27 2020 +0100

    New Trickbot wermgr rule

$ python tools/sigmac -r -t fieldlist rules/windows/
An unsupported feature is required for this Sigma rule (rules/windows/powershell/powershell_invoke_obfuscation_obfuscated_iex.yml): Map values must be strings, numbers or lists, not <class 'sigma.parser.modifiers.type.SigmaRegularExpressionModifier'>
Feel free to contribute for fun and fame, this is open source :) -> https://github.com/Neo23x0/sigma
```

Some of the rules that cause the error:
- `windows/powershell/powershell_invoke_obfuscation_obfuscated_iex.yml`
- `windows/process_creation/win_invoke_obfuscation_obfuscated_iex_commandline.yml`
- `windows/builtin/win_mal_creddumper.yml`

What is the recommended way of solving this?
Thanks!

**Comment by traut** [comment]
flag `-d` allows me to skip the failing rules but it's a workaround at best, not a solution

**Comment by thomaspatzke** [comment]
Fixed
