### ISSUE TITLE
Splunk Converter:  Splunk extracts EventID as EventCode

### ISSUE THREAD

**Issue by dstaulcu** [Neo23x0/sigma#16]
In my experience, the windows event log EventID is represented as EventCode within Splunk.  Might be worth considering outputting EventCode instead of EventID as part of the converter.

**Comment by thomaspatzke** [comment]
This is the reason for [field mappings](https://github.com/Neo23x0/sigma/wiki/Converter-Tool-Sigmac#field-mappings) in sigmac.
