### ISSUE TITLE
Logical operator problem in Splunk queries when a rule have multiple log sources

### ISSUE THREAD

**Issue by esebese** [Neo23x0/sigma#168]
Hi,
When I generate a rule which have multiple log sources (e.g Windows Security Event Log and Sysmon) to Splunk query, the query has no boolean logical operator between these field groups of separate log sources. Thus, the query means to Splunk there is an AND operator between these field groups. In this case, some servers do not run Sysmon and the whole query becomes meaningless by the nature of AND operator.  sourcetype="*" is OK but, wouldn't be better if OR operator placed between these field groups?
Thanks.

**Comment by thomaspatzke** [comment]
Ok, fine :)
