### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by megan201296** [Neo23x0/sigma#177]
FYSA, two of the same sig in `sigma/rules/windows/sysmon` due to variation in capitalization.

<img width="991" alt="screen shot 2018-10-01 at 3 17 34 pm" src="https://user-images.githubusercontent.com/19668285/46313324-28c72300-c58d-11e8-9d55-3a5b84156c7b.png">

**Comment by megan201296** [comment]
Same with `sysmon_powershell_amsi_bypass.yml` and `sysmon_powershell_dll_execution.yml`. Renamed with all lowercase but duplicate files were never deleted.

**Comment by Neo23x0** [comment]
This may be caused by our local git config. I can't see the files in my local HEAD of the master branch. I'll remove them in the Web GUI.

**Comment by Neo23x0** [comment]
It's fixed and thanks
