### ISSUE TITLE
Standardized formatting for layout

### ISSUE THREAD

**Issue by megan201296** [Neo23x0/sigma#183]
The order of different sections is very volatile. The one that stands out most to me is "tags". Sometimes its after detections, sometimes its after references (https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_mimikatz_detection_lsass.yml vs. https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_password_dumper_lsass.yml ).

I would like to submit a PR for getting iit more standardized but first wanted to see if a) there was a reason you wouldn't want it changed and b) which location is prefered for tags (before or after detection).

**Comment by thomaspatzke** [comment]
The inconsistent ordering was not intentional, cleaning this up would be nice! I'm a bit unsure about the best order, but think the best location would be at the top of the rule with all the other rule meta data, after the references.

@Neo23x0 what do you think about it?

**Comment by megan201296** [comment]
Your project your choice, but if we were voting I'd also say at the top for the exact reason you said, keep all the metadata together. Just my two cents. Let me know what you think.

**Comment by megan201296** [comment]
@thomaspatzke was thinking about this more... best idea would be to get a proper "schema" in place for the order of things like "status", "title" "description" , etc etc etc. for the documentation for writing rules so that its a) standardized all the way, not just tags as mentiooned here and b) it is futureproof

**Comment by savvyspoon** [comment]
@thomaspatzke If you update the specification to the schema that looks best I'll update the rules. 

https://github.com/Neo23x0/sigma/wiki/Specification

**Comment by savvyspoon** [comment]
@thomaspatzke  @megan201296  I created a little python script to standardize the schema. I just need to add the recursive path logic.
https://github.com/savvyspoon/SigmaYamlParser
