### ISSUE TITLE
Issue with sysmon cmstp rule logic

### ISSUE THREAD

**Issue by megan201296** [Neo23x0/sigma#185]
Have a question about this rule: https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_cmstp_com_object_access.yml

Based on the specification documentation, it seems the list under `ParentCommandLine:` would be considered a logical `OR`. However, based on the provided references, the conditions are intended to be `AND`. Let me know if I am incorrect in my understanding. If I am correct and there is an issue I am more than happy to submit the PR to fix it.

**Comment by thomaspatzke** [comment]
Fixed! Thanks, @megan201296!
