### ISSUE TITLE
Use of "platform" logsource in powershell logs

### ISSUE THREAD

**Issue by dstaulcu** [Neo23x0/sigma#19]
In most rules, you use the logsource.product field to describe the operating system type and the logsource.service field to describe the log sourcetype.  

With powershell, you use logsource.platform to describe the operating system type and logsource.product to describe the log sourcetype.  

This seems inconsistent.  Is platform going to be a thing or should the powershell rules be updated for consistency?

**Comment by thomaspatzke** [comment]
Fixed by @Neo23x0 in [this commit](https://github.com/Neo23x0/sigma/commit/055992eb05c4b35b32725949fdf96e7d6c07babd#diff-3cefabd09446c20a75c3dd25e8ce0872)
