### ISSUE TITLE
Es-dsl and es-qs wildcards incorrect

### ISSUE THREAD

**Issue by armoured-ape** [Neo23x0/sigma#194]
I tested the outputs of the sigma es-dsl and es-qs but they output with errors that mean they won't work.  While sytactically correct they handle * wildcards as string literals.  In the qs the terms shouldn't be in quotes.  In the dsl,  you need to use "wildcard" not "match_phrase".

**Comment by thomaspatzke** [comment]
Solution would be removal of quotes and escaping of spaces as described [here](https://stackoverflow.com/questions/42614303/using-wildcards-in-phrases-with-elasticsearch-query-string-query). Will implement and try this in the next days.

**Comment by thomaspatzke** [comment]
Just pushed a first fix to the master branch. Unfortunately I've discovered some further issues. In ES, wildcards match well in tokens, e.g. `*bar` also matches `foobar`. This doesn't works as expected across multiple tokens in analyzed fields, but seems to be fine with keyword fields. So the ES backend has to distinguish between:

* Values with wildcards: match in *keyword* field
* Values without wildcards: match in *analyzed* field

**Comment by thomaspatzke** [comment]
I had to move the change into a separate branch *issue-194*, as the generated ES queries seem to be wrong in some cases and CI testing failed.

**Comment by thomaspatzke** [comment]
Reverted to old behavior, as partial fix broke conversions of many other rules. Will push the full fix when it's done and tested.

**Comment by thomaspatzke** [comment]
Further experiments:

* `EventID:1 AND CommandLine:*\\system32\\conhost.exe\ 0xffffffff` doesn't matches.
* `EventID:1 AND CommandLine:"*\\system32\\conhost.exe\ 0xffffffff"` matches
* `LogProvider:"Microsoft\-Windows\-Sysmon" AND EventID:"8" AND StartAddress:*14E0` matches
* `LogProvider:"Microsoft\-Windows\-Sysmon" AND EventID:"8" AND StartAddress:"*14E0"` doesn't matches

So naive approach of looking after wildcards in values and quoting context-sensitively wouldn't work. Need to apply some heuristic that generates different queries depending on matching of token separators (?).

**Comment by thomaspatzke** [comment]
Some further experiments show the following solution works well:

* Usage of *keyword* fields (`fieldname.keyword`)
* Search value is not quoted
* Characters important to be escaped: colon `:`, whitespaces

Tests show that this doesn't introduces problems like described in #203

**Comment by neu5ron** [comment]
does SIGMA currently walk any indices to get the mappings? may be a consideration, because even if they there is no ".keyword" field but is still a "keyword", walking the mappings would still allow to apply.

**Comment by thomaspatzke** [comment]
No, it doesn't. I considered this for the fix of this issue but want to keep the conversion independent from the availability of the backends. The keyword field will be configurable by defining a suffix and blacklist. Further there will be a heuristic that determines the need for keyword field usage by the value.

**Comment by thomaspatzke** [comment]
Fixed for *es-qs* backend and backends that depend on this. Fix for *es-dsl* is pending.

Can you confirm the fix works for you, @armoured-ape?

**Comment by thomaspatzke** [comment]
Also fixed that for the *es-dsl* backend. Close the issue now, feel free to reopen if something is still wrong here.

**Comment by christophetd** [comment]
I'm having issues making the `es-dsl` backend work with a fresh elasticsearch install ingesting logs from Graylog.

Here's the query generated by `sigmac ./rules/windows/sysmon/sysmon_powershell_download.yml -t es-dsl`:

<details>
<summary>Elasticsearch query</summary>

```json
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "EventID": "1"
              }
            },
            {
              "wildcard": {
                "Image.keyword": "*\\powershell.exe"
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "wildcard": {
                      "CommandLine.keyword": "*new-object system.net.webclient).downloadstring(*"
                    }
                  },
                  {
                    "wildcard": {
                      "CommandLine.keyword": "*new-object system.net.webclient).downloadfile(*"
                    }
                  },
                  {
                    "wildcard": {
                      "CommandLine.keyword": "*new-object net.webclient).downloadstring(*"
                    }
                  },
                  {
                    "wildcard": {
                      "CommandLine.keyword": "*new-object net.webclient).downloadfile(*"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```


</details>


Although the index has a mapping so that the fields are all of "keyword" type, this query does not work. More specifically, it works perfectly if I remove the `.keyword` suffixes from the query, as follows:

<details>
<summary>Fixed Elasticsearch query</summary>

```json
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "EventID": "1"
              }
            },
            {
              "wildcard": {
                "Image": "*\\powershell.exe"
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "wildcard": {
                      "CommandLine": "*new-object system.net.webclient).downloadstring(*"
                    }
                  },
                  {
                    "wildcard": {
                      "CommandLine": "*new-object system.net.webclient).downloadfile(*"
                    }
                  },
                  {
                    "wildcard": {
                      "CommandLine": "*new-object net.webclient).downloadstring(*"
                    }
                  },
                  {
                    "wildcard": {
                      "CommandLine": "*new-object net.webclient).downloadfile(*"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```


</details>

A few more details:

- I tried with both a fresh install of ES 5.6.0 and 6.6.0 and experience the same issue
- Here is my complete index mapping for reference

<details>
<summary>Index mapping</summary>
```json

{
  "windows_0": {
    "mappings": {
      "message": {
        "dynamic_templates": [
          {
            "internal_fields": {
              "match": "gl2_*",
              "mapping": {
                "type": "keyword"
              }
            }
          },
          {
            "store_generic": {
              "match": "*",
              "mapping": {
                "index": "not_analyzed"
              }
            }
          }
        ],
        "properties": {
          "AccountName": {
            "type": "keyword"
          },
          "AccountType": {
            "type": "keyword"
          },
          "Category": {
            "type": "keyword"
          },
          "Channel": {
            "type": "keyword"
          },
          "CommandLine": {
            "type": "keyword"
          },
          "Company": {
            "type": "keyword"
          },
          "CreationUtcTime": {
            "type": "keyword"
          },
          "CurrentDirectory": {
            "type": "keyword"
          },
          "Description": {
            "type": "keyword"
          },
          "DestinationHostname": {
            "type": "keyword"
          },
          "DestinationIp": {
            "type": "keyword"
          },
          "DestinationIsIpv6": {
            "type": "keyword"
          },
          "DestinationPort": {
            "type": "keyword"
          },
          "DestinationPortName": {
            "type": "keyword"
          },
          "Details": {
            "type": "keyword"
          },
          "Domain": {
            "type": "keyword"
          },
          "EventID": {
            "type": "keyword"
          },
          "EventReceivedTime": {
            "type": "date"
          },
          "EventTime": {
            "type": "date"
          },
          "EventType": {
            "type": "keyword"
          },
          "FileVersion": {
            "type": "keyword"
          },
          "Hashes": {
            "type": "keyword"
          },
          "Hostname": {
            "type": "keyword"
          },
          "Image": {
            "type": "keyword"
          },
          "Initiated": {
            "type": "keyword"
          },
          "IntegrityLevel": {
            "type": "keyword"
          },
          "Keywords": {
            "type": "keyword"
          },
          "LogonGuid": {
            "type": "keyword"
          },
          "LogonId": {
            "type": "keyword"
          },
          "Message": {
            "type": "keyword"
          },
          "Opcode": {
            "type": "keyword"
          },
          "OpcodeValue": {
            "type": "keyword"
          },
          "ParentCommandLine": {
            "type": "keyword"
          },
          "ParentImage": {
            "type": "keyword"
          },
          "ParentProcessGuid": {
            "type": "keyword"
          },
          "ParentProcessId": {
            "type": "keyword"
          },
          "ProcessGuid": {
            "type": "keyword"
          },
          "ProcessID": {
            "type": "keyword"
          },
          "Product": {
            "type": "keyword"
          },
          "Protocol": {
            "type": "keyword"
          },
          "ProviderGuid": {
            "type": "keyword"
          },
          "RecordNumber": {
            "type": "keyword"
          },
          "Severity": {
            "type": "keyword"
          },
          "SeverityValue": {
            "type": "keyword"
          },
          "SourceHostname": {
            "type": "keyword"
          },
          "SourceIp": {
            "type": "keyword"
          },
          "SourceIsIpv6": {
            "type": "keyword"
          },
          "SourceModuleName": {
            "type": "keyword"
          },
          "SourceModuleType": {
            "type": "keyword"
          },
          "SourceName": {
            "type": "keyword"
          },
          "SourcePort": {
            "type": "keyword"
          },
          "TargetFilename": {
            "type": "keyword"
          },
          "TargetObject": {
            "type": "keyword"
          },
          "Task": {
            "type": "keyword"
          },
          "TerminalSessionId": {
            "type": "keyword"
          },
          "ThreadID": {
            "type": "keyword"
          },
          "User": {
            "type": "keyword"
          },
          "UserID": {
            "type": "keyword"
          },
          "UtcTime": {
            "type": "keyword"
          },
          "Version": {
            "type": "keyword"
          },
          "full_message": {
            "type": "text",
            "analyzer": "standard"
          },
          "gl2_remote_ip": {
            "type": "keyword"
          },
          "gl2_remote_port": {
            "type": "keyword"
          },
          "gl2_source_input": {
            "type": "keyword"
          },
          "gl2_source_node": {
            "type": "keyword"
          },
          "message": {
            "type": "text",
            "analyzer": "standard"
          },
          "source": {
            "type": "text",
            "analyzer": "analyzer_keyword",
            "fielddata": true
          },
          "streams": {
            "type": "keyword"
          },
          "timestamp": {
            "type": "date",
            "format": "yyyy-MM-dd HH:mm:ss.SSS"
          }
        }
      }
    }
  }
}
``` 
</details>

I would expect this to work on a default ES install - any insights @thomaspatzke? Thanks

**Comment by thomaspatzke** [comment]
Your mapping defines the main field as type keyword instead of defining a multi-field with a subfield keyword that also has the type keyword. Therefore no field.keyword exists within your mapping.

See the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html) for further reference.

**Comment by christophetd** [comment]
Thank you for the information. However, I think it would be worth it to add an option to the elastalert backend to not use the `.keyword` subfields? There's already an option not to use it for specific fields, but an option `use_keyword_subfields` which is true by default and could be disabled would make sense to me. 

What do you think?

**Comment by HarishHary** [comment]
> Further experiments:
> 
> * `EventID:1 AND CommandLine:*\\system32\\conhost.exe\ 0xffffffff` doesn't matches.
> * `EventID:1 AND CommandLine:"*\\system32\\conhost.exe\ 0xffffffff"` matches
> * `LogProvider:"Microsoft\-Windows\-Sysmon" AND EventID:"8" AND StartAddress:*14E0` matches
> * `LogProvider:"Microsoft\-Windows\-Sysmon" AND EventID:"8" AND StartAddress:"*14E0"` doesn't matches
> 
> So naive approach of looking after wildcards in values and quoting context-sensitively wouldn't work. Need to apply some heuristic that generates different queries depending on matching of token separators (?).

Hello, coming back on this issue. Isn't this related to the fact that wildcard on phrases don't work as we expect on ES ? I found the following link about wildcards and ES: https://www.timroes.de/elasticsearch-kibana-queries-in-depth-tutorial

Is it possible to know why the type "keyword" seems like the solution for wildcards ?

**Comment by duzvik** [comment]
sigmac convertor automatically(for es)  adds .keyword if it finds * in a detection section.

**Comment by HarishHary** [comment]
> sigmac convertor automatically(for es) adds .keyword if it finds * in a detection section.

Yes but why is it the solution for wildcards ?

**Comment by neu5ron** [comment]
will have solution very soon - there is a lot of one off testing currently being done, logic is all added. testing es-dsl and es-qs and all rules too, will update once PR is submitted

**Comment by architect00** [comment]
> will have solution very soon - there is a lot of one off testing currently being done, logic is all added. testing es-dsl and es-qs and all rules too, will update once PR is submitted

Do you have any updates on this? I'm getting confused with the sigma behavior around  .keyword/wildcard/match_phrase.

**Comment by Neo23x0** [comment]
We are confused by Elastic's every changing and inconsistent way to index the fields. 
They make it harder for us than any other target system - and we support many of them.

**Comment by architect00** [comment]
> We are confused by Elastic's every changing and inconsistent way to index the fields.
I totally unterstand. I do not understand the official documentation on this matter anymore. Lucene/KQL and DSL seem to behave completely different in some cases.

Could the new EQL abstraction be a solution to the field issues because of ECS and the endgame schemas? Has anyone played around with it yet?
