### ISSUE TITLE
Feedback from a MISP project perspective

### ISSUE THREAD

**Issue by adulau** [Neo23x0/sigma#2]
Feedback from a MISP project perspective, the Sigma intermediate language for the signature creation for different SIEM is really a great idea.

We (@iglocska and @adulau) quickly reviewed it and we can propose two steps (on a @MISPProject perspective):

- Creating a specific attribute type in MISP called Sigma which can be used just like YARA or Snort rule types. This is an easy step but It might not fully cover the full interesting use-case of Sigma. When your repository will be public, we will add the attribute in the next release of MISP.

- As as second step creating rules from CoA (Course of Action) could be really nifty. We need some additional work in MISP to support the objects and especially the ability to make a list of chain events. This requires more work on our side especially to see how we could generate such generic search rules from a series of misp-objects. But it's definitely doable.

I hope this helps.

Don't hesitate to provide feedback or tell us if you need specific requirements in MISP to support the use of Sigma.

PS: Do you think that we could propose in the future some additional fields in Sigma? If we see a specific need in MISP communities?

**Comment by Neo23x0** [comment]
Hi @iglocska @adulau,

I noticed that some replacements occur while adding sigma rule to a MISP event.

![screen shot 2017-06-28 at 09 20 38](https://user-images.githubusercontent.com/2851492/27626513-9daeac16-5be8-11e7-8cc6-3b17afb2ed18.png)

![screen shot 2017-06-28 at 09 20 28](https://user-images.githubusercontent.com/2851492/27626519-a3547a06-5be8-11e7-8d89-f7b6368add4a.png)

Is it possible to deactivate these replacement in Sigma rules?
 
- Florian

**Comment by adulau** [comment]
Good point. Fixed in current MISP HEAD https://github.com/MISP/MISP/commit/b95cf3e3071175ec253a4dbdd3cdd2eb7927419d Thank you.

**Comment by iglocska** [comment]
Hello there Florian, 
I've just pushed a fix for it, Sigma rules will avoid going through the validation.
