### ISSUE TITLE
Smart Sigmac Conditional Grouping

### ISSUE THREAD

**Issue by jthack** [Neo23x0/sigma#207]
A lot of the rules have overlapping conditions, i.e. Event ID: 7045 or 4697 for new service created/installed. 

If sigmac could read the input into memory and group them intelligently, this would increase the efficiency by A LOT.

For example, instead of 
```
If event_id == 7045 AND image == "malware.exe":
      fire_alert('malware')
If event_id == 7045 AND image == "blah":
      fire_alert('blah)
```
it would be output
```
If event_id == 7045:
      if image == "malware.exe":
         fire_alert('malware')
      if image == "blah":
         fire_alert('blah)
```

**Comment by 59e5aaf4** [comment]
Reducing a binary tree to a minimal set of conditions is NP-hard. Also, coding compilers is hard. I'm currently trying to write a 
```python
class SigmaConditionOptimizerDepth(SigmaConditionOptimizer):
```
which purpose is to reduce rules to their `OR(AND(NOT?(test)))` form, and it's not trivial. I'll share it when I'll succeed. If this happens.
