### ISSUE TITLE
Elastalert Integration - Unsupported feature 'near' aggregation operator not yet implemented

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Neo23x0/sigma#209]
Good afternoon SIGMA team,

When translating every SIGMA rule to the Elastalert rule format, I get the following message on a few loops (example below is for [sysmon_mimikatz_inmemory_detection.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_mimikatz_inmemory_detection.yml)

```
An unsupported feature is required for this Sigma rule (rules/windows/sysmon/sysmon_mimikatz_inmemory_detection.yml): None : The 'near' aggregation operator is not yet implemented for this backend
Feel free to contribute for fun and fame, this is open source :) -> https://github.com/Neo23x0/sigma
```
This behavior makes the Elastalert rule to be blank, so for now I just delete those empty files and continue translating the other ones.

This only happens on the following rules:
* [sysmon_mimikatz_inmemory_detection.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_mimikatz_inmemory_detection.yml)
* [win_susp_samr_pwset.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_samr_pwset.yml)

**Comment by Cyb3rWard0g** [comment]
Got it! Thank you for clarifying @thomaspatzke 👍 so, rules with that aggregation will not be able to be used for Elasticsearch queries event if SIGMAC supports it correct?

**Comment by Cyb3rWard0g** [comment]
The reason why I asked is to make sure I keep the logic in my code that removes the SIGMA rules that use the 'near' integration when translating SIGMA to Elastalert rule format. Thank you 👍

**Comment by thomaspatzke** [comment]
> so, rules with that aggregation will not be able to be used for Elasticsearch queries event if SIGMAC supports it very well for other backends correct?

In fact, *near* isn't currently implemented at all. For ES and friends I have an idea how this could work with the Watcher backend. Perhaps something similar could work for ElastAlert. For DSL I'm quite sure there is no possibility.
