### ISSUE TITLE
Uploading .yml

### ISSUE THREAD

**Issue by ycISI** [Neo23x0/sigma#219]
Hello, I have a few .yml files I would like to add to the repository. Is there a simple guide as to how I can go about uploading them? 

Thank you

**Comment by thomaspatzke** [comment]
Hi! [This guide](https://help.github.com/articles/adding-a-file-to-a-repository/) describes an easy way via the GitHub web interface. I'm looking forward for your contribution!

**Comment by Neo23x0** [comment]
But @thomaspatzke, he cannot upload to our repository. 

The steps are:
1. Fork the Sigma repo
2. Upload the files to the forked repository
3. Create a Pull Request from the Forked repository

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by thomaspatzke** [comment]
> But @thomaspatzke, he cannot upload to our repository.

Argh, right - expected that GitHub forks automatically...

**Comment by Neo23x0** [comment]
If you click "Edit" for a single file, yes, it does that.
