### ISSUE TITLE
sigmac  es-qs convertor

### ISSUE THREAD

**Issue by duzvik** [Neo23x0/sigma#229]
Problem on converting rules to es-qs query:

Seems reEscape pattern  is incorrect https://github.com/Neo23x0/sigma/blob/5645c75576453e988c7f5817073f7c8eb6bba0c1/tools/sigma/backends/elasticsearch.py#L71

Function cleanValue https://github.com/Neo23x0/sigma/blob/5645c75576453e988c7f5817073f7c8eb6bba0c1/tools/sigma/backends/mixins.py#L29    returns
` *\\System32\*`
 instead 
`*\\System32\\*`

How to reproduce:

1) create test.yml
`title: test`
`logsource:`
  `   product: windows`
  `   service: sysmon`
`detection:`
  `    filter:`
  `      Image:`
  `           - '*\System32\*'`
  `    condition: filter`

Run: `./sigmac --target es-qs  test.yml`
`
$ Image.keyword:(*\\System32\*)
`

Conversion to es-dsl gives expected  query
`./sigmac --target es-dsl test.yml`

`$
"wildcard": {
                "process_path.keyword": "*\\System32\\*"
              }
`

**Comment by thomaspatzke** [comment]
This is expected behavior. `\*` in Sigma rule gets special handling to be able to pass an escaped `*` to the generated query. Try if `\\*` gives you the expected result.

**Comment by duzvik** [comment]
Escaping of  `*` make sense to me. 
Any ideas on how to handle `\*` sequence?

`'*\System32\\*'` gives `*\\System32\\\*`  but expected is `*\\System32\\*`

**Comment by thomaspatzke** [comment]
Fixed this in master branch, the behavior is now as described in your last comment. Rule changes are pending.
Can you test it, please?

**Comment by duzvik** [comment]
"\\*" gives the expected result for --target es-qs 

But  --target es-dsl   gives  "*\\System32\\\\*" (extra  double slash.   expected   *\\System32\\*)

**Comment by thomaspatzke** [comment]
Fixed this. Please test and reopen if required.
