### ISSUE TITLE
[Feature Request] Add support for Azure Log Analytics

### ISSUE THREAD

**Issue by miriamxyra** [Neo23x0/sigma#233]
Please add Azure Log Analytics as a supported target for Sigma.
Examples of Log Analytics syntax can be found here: https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/get-started-queries

Thank you.

**Comment by Neo23x0** [comment]
See
https://gist.github.com/tuckner/9e1bd5f5d5d628bde7f427d1e596a4c2

Tweet
https://twitter.com/tuckner/status/1090286752772882432

**Comment by miriamxyra** [comment]
Thanks for connecting! Let's see how we can fix the Sysmon issue.

**Comment by thomaspatzke** [comment]
Seems a mix between WDATP syntax and the usual log events and @tuckner is on a good way :)

**Comment by tuckner** [comment]
Just for further clarity, whether I have it configured correctly or not I'm not positive, when Sysmon gets into ALA it is basically raw data in 'EventData' field. I had believed there needed to be a standard, backend work, and/or automated way to generate searchable fields like 'CommandLine'. These fields are normally created per Azure account Custom Fields with Azure's tool and can be named anything (and its a bit time consuming to configure). Perhaps Sigma could just assume something like 'CommandLine_CF' and use mapping files to accommodate custom configurations?

<img width="1089" alt="screen shot 2019-01-29 at 2 12 47 pm" src="https://user-images.githubusercontent.com/8551704/51937451-489e1480-23d0-11e9-94d3-c4695abe8a69.png">

<img width="1386" alt="screen shot 2019-01-29 at 2 27 53 pm" src="https://user-images.githubusercontent.com/8551704/51938375-8603a180-23d2-11e9-81e9-1a3e3fec7f63.png">

**Comment by tuckner** [comment]
Met with @miriamxyra, here are some take aways -

- @miriamxyra check internally to see if there could be a way to export/import Custom Fields, upload Custom Logs that are XML 'delimitered', and/or parse Sysmon natively in the platform (if so, perhaps they get joined to the SecurityEvents table or their own table?).
- @Neo23x0 @thomaspatzke - would it be a possibility/wanted to provide a Custom Field import file with this repo if ALA was capable of it?
- I will work on putting the finishing touches on the converter.

**Comment by thomaspatzke** [comment]
>     * @Neo23x0 @thomaspatzke - would it be a possibility/wanted to provide a Custom Field import file with this repo if ALA was capable of it?

Yes! I think this would fit well into the [contrib part of this repository](https://github.com/Neo23x0/sigma/tree/master/contrib), which is the location for useful stuff which is not part of the core.

**Comment by tuckner** [comment]
@miriamxyra brought my attention to two methods in the query language that allows parsing of logs in the query.

https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/parse-text
https://docs.microsoft.com/en-us/azure/kusto/query/parse-xmlfunction

So I believe the idea now is something like -

1.
<table>
| parse RawData with * " CommandLine=" CommandLine 
| where <sigma query ex. CommandLine = "whoami.exe">

or

2.
<table>
| extend data=parse_xml(RawData)
| where <sigma query ex. data["CommandLine"] = "whoami.exe">

For '1', perhaps there needs to be a reference to the Sysmon schema that is in use and in the converter add the capability to reference that schema.
For '2', there are limitations on the field size and possibly processing intensity but looks like it could be cleaner.

Will get some POCs tried out.

**Comment by tuckner** [comment]
Think I might've gotten it. Not entirely happy with it all, but it is functional and seems like it might not be slow at scale.  Pulls Sysmon schema from https://gist.github.com/olafhartong/761f471865e7d1c66fbb27d2e5ffa9f0 and uses it to create the parse fields like so:

```
Event
| parse EventData with * 'Data Name="RuleName">' RuleName '<' * 'Data Name="UtcTime">' UtcTime '<' * 'Data Name="ProcessGuid">' ProcessGuid '<' * 'Data Name="ProcessId">' ProcessId '<' * 'Data Name="Image">' Image '<' * 'Data Name="FileVersion">' FileVersion '<' * 'Data Name="Description">' Description '<' * 'Data Name="Product">' Product '<' * 'Data Name="Company">' Company '<' * 'Data Name="CommandLine">' CommandLine '<' * 'Data Name="CurrentDirectory">' CurrentDirectory '<' * 'Data Name="User">' User '<' * 'Data Name="LogonGuid">' LogonGuid '<' * 'Data Name="LogonId">' LogonId '<' * 'Data Name="TerminalSessionId">' TerminalSessionId '<' * 'Data Name="IntegrityLevel">' IntegrityLevel '<' * 'Data Name="Hashes">' Hashes '<' * 'Data Name="ParentProcessGuid">' ParentProcessGuid '<' * 'Data Name="ParentProcessId">' ParentProcessId '<' * 'Data Name="ParentImage">' ParentImage '<' * 'Data Name="ParentCommandLine">' ParentCommandLine '<' *
| where (EventID == "1" and CommandLine == "whoami")
```

Will clean some things up and submit a pull.


<img width="1432" alt="screen shot 2019-03-01 at 3 09 06 pm" src="https://user-images.githubusercontent.com/8551704/53666682-64e1db00-3c34-11e9-936c-56def4eceed2.png">
![screen shot 2019-03-01 at 3 10 00 pm](https://user-images.githubusercontent.com/8551704/53666683-657a7180-3c34-11e9-97ab-3d02b1f3743b.png)

**Comment by tuckner** [comment]
Created PR: https://github.com/Neo23x0/sigma/pull/275

@miriamxyra

**Comment by tuckner** [comment]
@miriamxyra looks like this has been merged, hopefully it will help you out!

**Comment by thomaspatzke** [comment]
Done by @tuckner, thanks for your contribution!
