### ISSUE TITLE
False positives with EventID overlaps

### ISSUE THREAD

**Issue by neu5ron** [Neo23x0/sigma#263]
There are some overlap of EventIDs in Channels such as Application and System, specifically I noticed in one environment that ` EventID:104 AND Channel:System`  was hitting this rule:
https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_eventlog_cleared.yml

I imagine this is rare, however I wanted to submit this as an issue to see what others thoughts/ideas because I would believe this may apply to more rules.

I am thinking maybe can add a NOT Subcategory/Category/SourceName to events in System/Application for a scenario where there is none -- and then more specific by adding Subcategory/Category/SourceName for event's where it applies in this example such as `Channel:System AND SourceName:Eventlog`

**Comment by thomaspatzke** [comment]
> specifically I noticed in one environment that ` EventID:104 AND Channel:System` was hitting this rule:
https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_eventlog_cleared.yml

This is exactly the purpose of this rule to match on System/104 events. Or do you mean there are application events with EventID 104? These shouldn't match with the query generated by a properly configured sigmac, as the logsource states that only the Windows System log is in scope:

```
logsource:
    product: windows
    service: system
```

> I am thinking maybe can add a NOT Subcategory/Category/SourceName to events in System/Application for a scenario where there is none

There are two ways to do this. by adding them directly to the rules or by log source definition and sigmac configuration. I think it depencds on the specific case.

**Comment by neu5ron** [comment]
There is another event/log in System with EID 104.
Sorry if Im causing confusion with interchangeabley using category &
sourcename.
In this scenario (the suspicious log clear rule) the “Log Name” is System.
But, as Im sure you know, there are specific “source name”s inside of a
channel/log-name like System (ie: another example is a Application - as you
mentioned). these are referred to as SourceName by winlogbeat and nxlog -
Microsoft calls them ProviderName.

Therefore, in this case; without specificying that the SourcName is
“Microsoft-Windows-Eventlog” AND LogName:Sysyem - it causes hits on any
event’s in System with EID 104.

I hope that clears it up..

**Comment by thomaspatzke** [comment]
I think for such ambiguities it would be the best to add the SourceName directly to the rule, as it's quite unspecific to the environment.

**Comment by thomaspatzke** [comment]
Fixed in rule.
