### ISSUE TITLE
sigmac to Elastalert problem

### ISSUE THREAD

**Issue by mikkel17** [Neo23x0/sigma#279]
Hello!
I am trying out HELK, and really like this Sigma concept. However I get a lot of events added to my elastalert index, as it seems the query generated with sigmac matches not only on `privilege::debug` but `privilege` or `debug`.

This is the rule: [win_alert_mimikatz_keywords.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_alert_mimikatz_keywords.yml)

The filter generated from sigmac (with "-t elastalert"):
```filter:
- query:
    query_string:
      query: (mimikatz OR mimilib OR 3\ eo.oe OR eo.oe.kiwi OR privilege\:\:debug
        OR sekurlsa\:\:logonpasswords OR lsadump\:\:sam OR mimidrv.sys)
```
~~I can fix it manually by changing it to `"privilege\\:\\:debug"`~~. The rule also matches on the number 3. This is just an example, other rules have similar behavior.

-Mikkel

I am unsure if this is the same behavior or if it was solved here: #203

**Comment by mikkel17** [comment]
I know it's not privilige::debug, but same concept in following example. I took the query from earlier post, and here it matches on "3" and "SAM".

![elastalert](https://user-images.githubusercontent.com/34633670/54111938-5be7cb00-43e5-11e9-834a-e68caa5bac6c.PNG)

**Comment by Neo23x0** [comment]
The query is broken. @thomaspatzke will look at it as soon as he finds the time.

**Comment by thomaspatzke** [comment]
Duplicate to #343 - I close this one and use the other issue to track this.
