### ISSUE TITLE
Change field that is created in the elastic rule conversion - How? (field mapping doesn't seem helpful here)

### ISSUE THREAD

**Issue by sahar55** [Neo23x0/sigma#288]
Hi, I'm new to sigma so I may have missed something although I've read the documentation several times and written mappings and rules yet I have failed to solve this one. 

When I convert a rule, let's say to the elasticsearch format, the field that holds the source of the log is named "EventLog". 
**Example:**
`sigmac.py --target es-qs --config config\elk-windows.yml "some_rule.yml`
The result query contains "**EventLog**:"Microsoft\-Windows\-Sysmon""

I need to change that field (EventLog) to something else since it is named differently on my elastic system. so instead of **EventLog** ill have something like **LogSource**
I have attempted adding a mapping in the fieldmapping section at the config file, with no success. 

any suggestions on how to change that?

**Comment by thomaspatzke** [comment]
Just adapt the config to your needs. In the specific case replace `EventLog` occurrences with `LogSource` or whatever you need.
