### ISSUE TITLE
Usage of list of values in Sigma

### ISSUE THREAD

**Issue by kiranmanikkoth** [Neo23x0/sigma#289]
Hi Team,

We are trying to write a sigma rule to find certain traffic initiated towards some malicious destination either by destination IPs or destination domain lookup.

So we'd like to check the particular destination IP/Domain from a list (e.g, Active list in ArcSight & Reference set QRadar) where the malicious Domain/IP is already stored.

How can I achieve this list lookup in Sigma?

**Comment by Neo23x0** [comment]
1. You have to decide in which log to look for it: Firewall, Proxy, DNS
2. Depending on the log, you then select a field name by looking at examples that are already in the rule set (e.g. see https://github.com/Neo23x0/sigma/blob/master/rules/proxy/proxy_download_susp_dyndns.yml) or take the field names in your log 

in general: 
Sigma is not meant to just match huge lists of IOCs (e.g. >100). Simple IOC matching is boring stuff and every product has its own best practice application for that use case. You mentioned e.g. "Active Lists" in ArcSight, splunk uses "Lookups" and so on. 

If you browse through the rule set, you'll note that most rules (>90%) are generic rules that match a certain behaviour or method. Those are the valuable rules that we try to create. We often note that rules that we've created years ago cover the most recent threats. 

Emotet droppers are a good example (see https://twitter.com/cyb3rops/status/1071127750596067329). AV detection rate is low but the process tree in which `WINWORD.EXE`  starts `cmd.exe` is covered by a rule created in April 2018. 

So there are 2 disciplines: 
A. Mass matching IOCs and fields in logs 
B. Generic method detection with Sigma

I hope, that helped.
