### ISSUE TITLE
Grep set rules not properly created with complex rules

### ISSUE THREAD

**Issue by javierDAW** [Neo23x0/sigma#290]
Apparently when generating grep rules with more than one fields inside selection fields, sigmac does not manage the parenthesis distribution properly.

By compiling the following rule, which has more than one fields inside "selection1" (Image and CommandLine) generates a PERL regex with the parenthesis non properly distributed:

**win_bypass_squiblytwo.yml**

title: SquiblyTwo
status: experimental
description: Detects WMI SquiblyTwo Attack with possible renamed WMI by looking for imphash
references:
    - https://subt0x11.blogspot.ch/2018/04/wmicexe-whitelisting-bypass-hacking.html
    - https://twitter.com/mattifestation/status/986280382042595328
tags:
    - attack.defense_evasion
    - attack.t1047
author: Markus Neis / Florian Roth
falsepositives:
    - Unknown
level: medium
logsource:
    category: process_creation
    product: windows
detection:
    selection1:
        Image:
            - '*\wmic.exe'
        CommandLine:
            - wmic * *format:\"http*
            - wmic * /format:'http
            - wmic * /format:http*
    selection2:
        Imphash:
            - 1B1A3F43BF37B5BFE60751F2EE2F326E
            - 37777A96245A3C74EB217308F3546F4C
            - 9D87C9D67CE724033C0B40CC4CA1B206
        CommandLine:
            - '* *format:\"http*'
            - '* /format:''http'
            - '* /format:http*'
    condition: 1 of them

**Generated REGEX**

grep -P '^(?:.*(?:.*(?:.*(?=.*(?:.*.* .*format:\"http.*|.*.* /format:'http|.*.* /format:http.*))(?=.*(?:.*1B1A3F43BF37B5BFE60751F2EE2F326E|.*37777A96245A3C74EB217308F3546F4C|.*9D87C9D67CE724033C0B40CC4CA1B206)))|.*(?:.*(?=.*(?:.*wmic .* .*format:\"http.*|.*wmic .* /format:'http|.*wmic .* /format:http.*))(?=.*(?:.*.*\wmic\.exe)))))'

**Basic python code to test it:**

import re

list = []

f = open("test", "r")
for x in f:
        regex =  (x.split("'"))[1].split("'")[0]
        print(regex)
        list.append(re.compile(r'%s' % regex))

**python regexSearcher.py**

Traceback (most recent call last):
  File "regexSearcher.py", line 9, in <module>
    list.append(re.compile(r'%s' % regex))
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis

**Comment by thomaspatzke** [comment]
The issue are not encoded single quotes. Parentheses seem to be balanced correctly. Fix ongoing.

**Comment by thomaspatzke** [comment]
Fixed. Output of `'` as `'"'"'`
