### ISSUE TITLE
Sigma rules correlation 

### ISSUE THREAD

**Issue by azarzar15** [Neo23x0/sigma#291]
Hi Team,

I was wondering about triggering alerts that require a set of two different sigma rules (each one from a different log source with different conditions).

would you consider it as the SIEM analyst duty to write such correlation after the conversion from the different sigma rules for its relevant SIEM product has been done?  or it could be maybe an abstraction layer for correlating between sigma rules?

Thanks for the amazing work with this project.

Or A.

**Comment by thomaspatzke** [comment]
The *near* operator ([bottom of this section](https://github.com/Neo23x0/sigma/wiki/Specification#condition)) does this inside a single rule. Unfortunately this is currently not supported by most (or all) backends.
