### ISSUE TITLE
Specification lags definiton of semantics for YAML files containing multiple multiple documents 

### ISSUE THREAD

**Issue by kidmose** [Neo23x0/sigma#293]
In the process of parsing rule files to get an overview of what log sources are used, I find that not all documents have the mandatory `logsource` entry.

For the following files, the first document is missing it, while the following documents in the same file has it:

    sigma/rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml
    sigma/rules/windows/sysmon/sysmon_sysinternals_eula_accepted.yml
    sigma/rules/apt/apt_pandemic.yml
    sigma/rules/apt/apt_slingshot.yml
    sigma/rules/windows/process_creation/win_mal_adwind.yml
    sigma/rules/windows/sysmon/sysmon_cmstp_execution.yml
    sigma/rules/apt/apt_chafer_mar18.yml
    sigma/rules/windows/builtin/win_net_ntlm_downgrade.yml
    sigma/rules/apt/apt_unidentified_nov_18.yml
    sigma/rules/windows/sysmon/sysmon_dns_serverlevelplugindll.yml
    sigma/rules/windows/other/win_tool_psexec.yml

For this one, it is the other way around, with first document providing a `logsource` while the subsequent documents in the file don't:

    sigma/rules/apt/apt_turla_commands.yml

Is there some un-document (or at least not known to me) inheritance semantic?
I.e. in a multi-document file, the first document is some form of template, and the following document "fill" the template to form valid documents that meet the spec.

**Comment by kidmose** [comment]
This snippet might be useful if you want to reproduce the above finding:

    import yaml
    import glob
    
    # Load
    files = glob.glob('sigma/rules/**/*.yml', recursive=True)
    documents = {}
    for f in files:
        with open(f) as fd:
            documents[f] = list(yaml.safe_load_all(fd))
    
    print('Total rules: %s' % sum([len(v) for k, v in documents.items()]))
    
    print('Use of log sources:')
    for l in [(file, rule_number, len(document)) for file, document in list(documents.items())[:] for rule_number, rule in enumerate(document) if 'logsource' not in rule]:
        print(l)

With output:

    Total rules: 294
    Use of log sources:
    ('sigma/rules/windows/sysmon/sysmon_stickykey_like_backdoor.yml', 0, 3)
    ('sigma/rules/windows/sysmon/sysmon_sysinternals_eula_accepted.yml', 0, 3)
    ('sigma/rules/apt/apt_pandemic.yml', 0, 3)
    ('sigma/rules/apt/apt_slingshot.yml', 0, 3)
    ('sigma/rules/windows/process_creation/win_mal_adwind.yml', 0, 4)
    ('sigma/rules/windows/sysmon/sysmon_cmstp_execution.yml', 0, 3)
    ('sigma/rules/apt/apt_turla_commands.yml', 1, 3)
    ('sigma/rules/apt/apt_turla_commands.yml', 2, 3)
    ('sigma/rules/apt/apt_chafer_mar18.yml', 0, 5)
    ('sigma/rules/windows/builtin/win_net_ntlm_downgrade.yml', 0, 3)
    ('sigma/rules/apt/apt_unidentified_nov_18.yml', 0, 3)
    ('sigma/rules/windows/sysmon/sysmon_dns_serverlevelplugindll.yml', 0, 3)
    ('sigma/rules/windows/other/win_tool_psexec.yml', 0, 3)

**Comment by thomaspatzke** [comment]
> Is there some un-document (or at least not known to me) inheritance semantic?

Yes, they are called *rule collections* and are specified [here](https://github.com/Neo23x0/sigma/wiki/Specification#rule-collections).
