### ISSUE TITLE
Distinct count as aggregation function

### ISSUE THREAD

**Issue by P4T12ICK** [Neo23x0/sigma#302]
Add a distinct count as aggregation function in order to develop detection rules, which should trigger when multiple different events triggered but not several times the same trigger.

**Comment by thomaspatzke** [comment]
Try *dc* as aggregation operator. At least for Splunk this was already implemented but not yet documented.

**Comment by P4T12ICK** [comment]
Thanks for the answer. For the following condition: keywords | dc() by host > 6 , I still get a parser error with Unexpected Token ID 'dc'.

**Comment by thomaspatzke** [comment]
See #308
