### ISSUE TITLE
GraphQL/Neo4J Cypher sigmac backend

### ISSUE THREAD

**Issue by yampelo** [Neo23x0/sigma#306]
I'm working on a project (https://github.com/yampelo/beagle) which allows people to transform security data into graph structures, i'd love to add support for writing detections/queries that can take advantage the graph structures, and I think leveraging all the existing sigma contributions makes the most sense.

I think this might allow people to write detections at more than one tier of data, for example, this (https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_office_shell.yml) rule looks for only on level of interaction (`office application - [launches] -> shell`) but you might be able to make a signature that looks for even more specific behavior by looking for something like this:

```
office_application - [Launches] -> shell -> [Writes] -> File 
                                        \                /
                                            [launches]            
```

![image](https://user-images.githubusercontent.com/6065272/55630370-82e6b200-5783-11e9-884f-d303cb78634f.png)

which looks for an office application launching a shell, which then executes and launches the same file.

This might also allow for the chaining of rules, where if one rule matches, you can run the next on the next subgraph (which represents activity that could've only happened because of the first rule)

Just throwing out the idea, i'd love to integrate detections through sigma rather than rolling my own, what do you guys think?

**Comment by thomaspatzke** [comment]
Oh nice, Beagle is on my "Must try" list 😉 

I like the idea of graphs and the relationships introduced by them, but this would add features to Sigma that can only be used by few backends. Our main focus is to keep the feature set at a level that is supported by most SIEM (or similar) systems.

@Neo23x0 what do you think about this?

**Comment by yampelo** [comment]
Let me know what you guys think! Worst case, If I roll my own, i'll just support the sigma format
