### ISSUE TITLE
Aggregation problems with count() and dc()

### ISSUE THREAD

**Issue by P4T12ICK** [Neo23x0/sigma#308]
I want to report a problem with the aggregation operators count() and dc().
When I run a sigma rule with the following condition:

condition: selection | **count**(val1) by val2 > 1000

I receive the following splunk search after conversion:
... | eventstats **dc**(val1) as val by val2 | search val > 1000

If I use the following condition:

condition: selection | **dc**(val1) by val2 > 1000

I receive an error message after conversion to a splunk search:
Sigma parse error in lnx_shell_test.yml: Unexpected token [ Token: ID: 'dc' ] at 13 in aggregation expression

**Comment by thomaspatzke** [comment]
I see the problem. Someone added a *dc* operator to the Splunk backend where I looked whis up, but the Sigma condition tokenizer is not aware about this. I will add a *distinct_count* aggregation (I prefer the clearer naming instead of shortcuts) and change the Splunk backend accordingly.

**Comment by thomaspatzke** [comment]
Ah, wait, the distinct count already is specified implicitely if a field name is given:

```
  All aggregation functions except count require a field name as parameter. The count aggregation counts all matching events if no field name is given. With field name it counts the distinct values in this field.
```

So count(field) should already be the distinct numbers of values in field. Perhaps the Splunk backend is wrong here.

**Comment by thomaspatzke** [comment]
One rule uses this:
```
$ tools/sigmac -t splunk rules/linux/lnx_susp_failed_logons_single_source.yml
(pam_message="authentication failure" pam_user="*" pam_rhost="*") | eventstats dc(pam_user) as val by pam_rhost | search val > 3
```

Is this the expected result?

**Comment by P4T12ICK** [comment]
In my opinion, the condition: selection | count(pam_user) by pam_rhost should create the following splunk search:
(pam_message="authentication failure" pam_user="*" pam_rhost="*") | eventstats count(pam_user) as val by pam_rhost | search val > 3

and the condition: selection | distinct_count(pam_user) by pam_rhost should create the following Splunk search:
(pam_message="authentication failure" pam_user="*" pam_rhost="*") | eventstats dc(pam_user) as val by pam_rhost | search val > 3

Answering your question: The result is not expected because count is used as an aggregation operator in Sigma and dc (distinct count) is shown in the Splunk search for the rule: rules/linux/lnx_susp_failed_logons_single_source.yml

I think both aggregation functions are important for Use Case development. Thank you for your support.

**Comment by thomaspatzke** [comment]
This would be a breaking change, as the semantic of count() is already defined in this way in Sigma. The behavior of counting events where a field is set could be implemented in a Sigma rule by directly searching for events with this field (`fieldname: *`) and counting the result with count() (without a field name).

**Comment by P4T12ICK** [comment]
Okay, thank you for the feedback. 
For clarification, if I use count() it will create an eventstats count and if I use count(val) it will create an evenstats dc. Did I understand it correct?

**Comment by thomaspatzke** [comment]
Yes, that is the intended behavior. If the converter behaves different, this might be a bug.

Sorry for the confusion!

**Comment by P4T12ICK** [comment]
Thank you.
