### ISSUE TITLE
backend-config option not working

### ISSUE THREAD

**Issue by j91321** [Neo23x0/sigma#331]
Hi,

I'm having trouble using the sigmac with --backend-config option as described in wiki. https://github.com/Neo23x0/sigma/wiki/Converter-Tool-Sigmac

I tried to stick to the wiki example as close as I could, but still didn't manage to replicate the result. The backend_config.yml just gets appended and doesn't really change the alert part of rule output as shown there.

Is there something I'm missing? 

```
root@sigma:~/sigma# cat backend_config.yml
emails: alerts@mydomain.tld
smtp_host: smtp.google.com
from_addr: noreply@mydomain.tld
expo_realert_time: 10m
root@sigma:~/sigma# echo $RULE
rules/windows/builtin/win_susp_sam_dump.yml
root@sigma:~/sigma# python3 tools/sigmac $RULE -t elastalert --backend-config backend_config.yml -c tools/config/elk-winlogbeat.yml
from_addr noreply@mydomain.tld
smtp_host smtp.google.com
emails alerts@mydomain.tld
expo_realert_time 10m
alert:
- debug
description: Detects suspicious SAM dump activity as cause by QuarksPwDump and other
  password dumpers
filter:
- query:
    query_string:
      query: (*\\AppData\\Local\\Temp\\SAM\-*.dmp\ * AND event_id:"16")
index: winlogbeat-*
name: SAM-Dump-to-AppData_0
priority: 2
realert:
  minutes: 0
type: any

```

**Comment by thomaspatzke** [comment]
The example in the wiki missed the selection of the alert method, fixed it. Further removed the debugging code that caused the output of the backend configuration.
