### ISSUE TITLE
win_susp_powershell_enc_cmd: Whitespace in commandline

### ISSUE THREAD

**Issue by mschilt** [Neo23x0/sigma#333]
Recent EMOTET waves use some whitespace to further obfuscate the Commandline. Examples: 
```
 powErSHell       -e    JABwADkAMAA4ADYAO..
 powErSHell       -e    JABHADYA..
 powErSHell       -e    JABiADMAMA..
 powErSHell       -e    JABEADcANAA0A..
```

All samples I saw use the same amount of spaces so just adding the pattern '* -e    JAB*' to the list could be a quick&dirty way of adding these but I suspect that they will use a different amount of whitespaces the next time.

Something like "powershell\s\-e\sJAB*" should do the trick but I doubt that all backends do support regexes. 

Adding all possible combinations of spaces (before and after -e) could be possible but is not very elegant.
```
'* -e JAB*'
'* -e  JAB*'
'* -e   JAB*'
'* -e    JAB*'
'* -e     JAB*'
'* -e      JAB*'
```
.. 

Ideas?

**Comment by Neo23x0** [comment]
Sorry for the very late reply. I was waiting for the Regex modifier. But I guess that the most efficient way is still the less elegant way that you've described. 

https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_powershell_enc_cmd.yml
