### ISSUE TITLE
sysmon_susp_net_execution.yml

### ISSUE THREAD

**Issue by woanware** [Neo23x0/sigma#34]
If powershell runs "net user" then under my ElasticSearch/Kibana stack, the data is represented like so:

- parent_cmdline: "C:\WINDOWS\system32\net.exe"
- image: C:\Windows\System32\net1.exe
- cmdline: C:\WINDOWS\system32\net1 user

I think the following conditions provide more flexibility:

```
Image:
    - '*\net.exe'
    - '*\net1.exe'

CommandLine:
    - ' group*'
    - ' localgroup*'
    - ' user*'
    - ' view*'
    - ' share'
    - ' accounts*'
    - ' use*'
```

**Comment by Neo23x0** [comment]
Done - thanks
