### ISSUE TITLE
AND statments 

### ISSUE THREAD

**Issue by honey4sec** [Neo23x0/sigma#347]
Is there a god way to use and statements insted of OR statments in fields ?
Insted of doing things like 

detection:
    layer_1:
        commandline: 
            - "net use"
        file_path:
    layer_2:
        commandline:
            - "/p:"
    layer_3:
        commandline:
            - "/u:"
    condition: layer_1 AND layer_2 AND layer_3

it would be nice to be able to segment peices of the query under one "layer"

eks:
detection:
    layer_1:
        commandline: 
            - "net use"
        commandline:
            - "/p:"
        commandline:
            - "/u"
    condition: layer_1

or:
    layer_1:
        commandline: 
            | "net use"
            |"/p:"
            | "/u"
    condition: layer_1

pipes or other statments as and

**Comment by thomaspatzke** [comment]
I'm currently working on a feature called *value modifiers* that will solve exact such problems. The solution will look like this:
```
detection:
  layer:
    commandline|all:
      - a
      - b
      - c
```

The list values will then be AND-linked. I'll keep you informed in this issue about the release.

**Comment by thomaspatzke** [comment]
Implemented by value modifiers as described above.
