### ISSUE TITLE
Question on complex searches and the future of Sigma

### ISSUE THREAD

**Issue by SRJanel** [Neo23x0/sigma#352]
Hello, I have a question.

On the README page of the Sigma repo, it says that Sigma is "covering more than 90% of the day-to-day needs". That phrase indicates (correct me if I am wrong) that Sigma has been built to address easy, not complex rules which can later be shared. Although from experience, I see that most of the companies use very specific and complex rules usually with many aggregations, rather than easy ones. For example one "complex" rule might be the following one (it is just an example and nothing more, I am aware that it does not make sense):

```

sourcetype=access_* status=200 action=purchase [search sourcetype=access_* status=200 action=purchase | top limit=1 clientip | table clientip] | bin span=5m _time | eval list=a-b | stats count, distinct_count(productId), values(productId) by _time clientip list
```

Maybe I am wrong, but I do not think that Sigma is able to convert the above rule. Hence, unfortunately, I cannot use Sigma for "complex" rules across two different SIEM technologies. I would like to know if Sigma is going to be able to address that 10% in future versions or if the philosophy of Sigma is going to be kept as it is (simple rules)? How do you see Sigma in a few years from now?

Thanks for your time.

**Comment by thomaspatzke** [comment]
The general strategy is to keep Sigma simple and don't cover such complex queries. We will improve over time and make it possible to cover few more use cases in the future (e.g. I'm currently working on an extension of Sigma that enables it to express regular expressions). It's not planned to implement more aggregation features, as this also makes it much harder to keep it compatible to different target languages.

**Comment by Neo23x0** [comment]
I'd like to add a short note: 

Other query languages start with a very flexible and therefore complex specification, which allows almost any expression and condition without any idea how to translate these complex generic queries into a specific query for all supported SIEM backends. 

Sigma was developed from front to back. It focuses on the practical applicability.
We integrate features in the query language whenever a significant number of backends is able to support that feature.
