### ISSUE TITLE
New release of sigmatools?

### ISSUE THREAD

**Issue by christophetd** [Neo23x0/sigma#358]
Hello, 

The latest release of sigmatools (0.10) was made on March 16, 2 months ago. There has been [30+ commits](https://github.com/Neo23x0/sigma/commits/master/tools) since then, including bug fixes to some backends.

Would it be possible to make a new release in order to make the changes available in [Pypi](https://pypi.org/project/sigmatools/)?

Thanks.

**Comment by thomaspatzke** [comment]
Just released 0.11.

**Comment by christophetd** [comment]
Thanks! As a suggestion, maybe it would make sense to make a Github release as well so people can see 0.11 in the "Releases" tab?

**Comment by thomaspatzke** [comment]
Forgot to push the tag, fixed this.
