### ISSUE TITLE
--backend-config option not available

### ISSUE THREAD

**Issue by ipninichuck** [Neo23x0/sigma#362]
Hello,

   When I updated my sigma tools to the most recent update the --backend-config option was no longer being accepted. I reverted back to the older version and the option worked just fine. Is this intentional or is the option not working properly in the update.

**Comment by thomaspatzke** [comment]
Works for me with the *ala* backend test config. Can you provide the exact command line and backend config that doesn't works?

**Comment by thomaspatzke** [comment]
Tested again with other config/backend, still not reproducible. Therefore I close this now. Improved the `--backend-config` help text.
