### ISSUE TITLE
[Feature Request] Add support for xpack-watcher "webhooks"

### ISSUE THREAD

**Issue by herrBez** [Neo23x0/sigma#364]
Currently, the xpack-watcher backend supports only `mail` as action while xpack-watchers [support different types of actions](https://www.elastic.co/guide/en/elastic-stack-overview/current/action-conditions.html), in particular `webhooks`.

It would be great to add support for other actions. The idea is to generate automatically watchers that contain these kinds of actions:
```json
  "actions": {
    "name of the action": {
      "webhook": {
        "scheme": "http",
        "host": "localhost",
        "port": 8080,
        "method": "post",
        "path": "/event/foo",
        "params": {
          "token": "123"
        },
        "headers": {},
        "body": "{{#toJson}}ctx.payload{{/toJson}}"
      }
    }
  }
```

**Comment by ipninichuck** [comment]
I was looking at this earlier too. I am currently working with xpack-watcher and will be using webhooks in my project. I noticed that the method used in the Elastalert portion further down in the elasticsearch.py should be a good guide of how to add this to the watcher portion. I am adding this to my list of things to do and hopefully will soon unless someone beats me to it...lol.

**Comment by herrBez** [comment]
Hi, you can take a look to my [attempt to implement this feature](https://github.com/herrBez/sigma/tree/xpack-webhook-option). If you want you can take inspiration from it (currently, it accepts some additional options) or even better we can work together to make an acceptable contribute to sigma.

**Comment by sacx** [comment]
I also made something. I also added index action. I made a pull request. Will see if it will be approved
https://github.com/Neo23x0/sigma/pull/379

**Comment by thomaspatzke** [comment]
Merged the PR from @sacx
