### ISSUE TITLE
Negative Values /NOT

### ISSUE THREAD

**Issue by JayPowerUser** [Neo23x0/sigma#367]
This is a great tool and I am really enjoying using it, I have one question. Is there a way to negative values like NOT ? 
I tried ```-``` ```!``` , but I haven't seen how to accomplish this with a wildcard. I can edit the queries later, but was seeing if this option is available. 

Thanks,

**Comment by thomaspatzke** [comment]
It's possible by a *not* condition. [Here's](https://github.com/Neo23x0/sigma/blob/a82ea0a02238952d3e7f50d18d0a291f222e4411/rules/windows/process_creation/win_susp_taskmgr_parent.yml) an example for this.

**Comment by JayPowerUser** [comment]
@thomaspatzke great thanks for the reference.
