### ISSUE TITLE
Rule ID and versionning

### ISSUE THREAD

**Issue by l0x-c0d3z** [Neo23x0/sigma#374]
We're considering using Sigma as a standard syntax for our internal IDS rules. In order to implement rule management in our system, we need additionnal metadata fields. We need to track a rule's history.

One way to do this which we will be prototyping is using tags with our own namespace. However the parsing required to extract the data we're looking for is a bit annoying.

Although I'd love to have top level fields called `uuid` and `version`, it would be nice and maybe more generic to have a kubernetes-style `labels` field that would contain an arbitrary key-value map.

**Comment by thomaspatzke** [comment]
We intentionally left Sigma open for custom extensions and incorporate them into the standard if they might be useful for more users. So far we used Git for versioning  and the file names for identification, but feel free to add new fields to your rules. Both, *uuid* and *version* are currently not used for any purpose at the top level of Sigma rules, therefore you can add them without any side-effect.
