### ISSUE TITLE
Sigma as detection code

### ISSUE THREAD

**Issue by fryguy04** [Neo23x0/sigma#376]
Question: Instead of having Sigma convert analytics to a SIEM language (Splunk, ELK, etc). Is there any way to use this as straight detection logic.  Example if I had a cloud scalable (containerized) way of executing Python code on many TB of Json or Pandas (evtx logs). Could I convert the Sigma library to straight up detect if a Log (json) matched the criteria (without having splunk/elk)? 

I guess what I'm asking ... can Python be an output "target".  

Open to thoughts / ideas of why this may or may not be a good idea

**Comment by juju4** [comment]
grep and powershell are targets. so no reason python can't IMO. just need the backend to be coded.

**Comment by thomaspatzke** [comment]
You could write a backend that generates code in your preferred language or use Sigma as library and build your matching logic around the internal logic tree representation of a Sigma rule.

> I guess what I'm asking ... can Python be an output "target".

The Sigma converter and the library are written in Python so this should be the easiest way.
