### ISSUE TITLE
 No detection definitions found

### ISSUE THREAD

**Issue by ianycxu** [Neo23x0/sigma#386]
When I try to modify pull-sigma.sh in order to convert linux sigma rules into elastalert rules by sigmac, the following error logs appears:

Working on Folder: rules/linux/lnx_buffer_overflows.yml:
 -------------------------------------------------------------
[+++] Processing linux rule: rules/linux/lnx_buffer_overflows.yml/* ..
Sigma parse error in /Users/.../esalert/rules/sigma_lnx_auditd_susp_cmds.yml: No detection definitions found

Do you know what this error means or how to fix it? Thank you.

**Comment by Neo23x0** [comment]
The rule looks wrong. I'll try to fix it.

**Comment by ianycxu** [comment]
I figured out that the error can be solved by adding another for loop in pull-sigma.sh file.

```
for  rule_category in rules/linux/* ; do
    echo " "
    echo "Working on Folder: $rule_category:"
    echo "-------------------------------------------------------------"
    for rule in $rule_category/* ; do
        echo "[+++] Processing linux rule: $rule .."
        tools/sigmac -t elastalert -c $ESALERT_HOME/sigmac/sigmac-config.yaml -o $ESALERT_HOME/rules/sigma_$(basename $rule) $rule
    done
done
# another for loop
for  rule in rules/linux/* ; do
    echo "[+++] Processing linux rule: $rule .."
    tools/sigmac -t elastalert -c $ESALERT_HOME/sigmac/sigmac-config.yaml -o $ESALERT_HOME/rules/sigma_$(basename $rule) $rule
done
```

The rule itself should be correct then. Thank you.
