### ISSUE TITLE
alert_hacktool_use rule is not correct

### ISSUE THREAD

**Issue by vitalisec** [Neo23x0/sigma#396]
Question on the following rule:
https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_alert_hacktool_use.yml

Description of the rule states: " This method detects well-known keywords, certain field combination that appear in Windows Eventlog when certain hack tools are used"

The way the example rule(s) are written, it is looking for a workstation name for the "Ruler" hacking tool.  This does not make sense.  Am I missing something with this rule?

**Comment by thomaspatzke** [comment]
@Neo23x0 I think the intention was a rule for suspicious workstation names? If yes, we should add the name "Kali", else this rule should be rebranded more specific to the ruler tool.

**Comment by Neo23x0** [comment]
Uh, that's a very old rule. I'll rework it.

**Comment by Neo23x0** [comment]
Transformed into 
https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_alert_ruler.yml
