### ISSUE TITLE
Help with elastalert conversion

### ISSUE THREAD

**Issue by mancharagopan** [Neo23x0/sigma#403]
Hi,
I am new to sigma, how do i convert sigma rule to elastalert and is there any documentation to sigma usage?

**Comment by thomaspatzke** [comment]
Basically: `tools/sigmac -t elastalert -c elk-winlogbeat -rI rules/windows/`
Help: `tools/sigmac --help`
And there's the [wiki](https://github.com/Neo23x0/sigma/wiki).
