### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by mancharagopan** [Neo23x0/sigma#405]
I am trying to implement this and seeking support but no response from the community or the team. Is this a dead project? am i wasting time on this project?

**Comment by Neo23x0** [comment]
You asked a question that could have been answered by reading the README or Wiki. 

> "I am new to sigma, how do i convert sigma rule to elastalert and is there any documentation to sigma usage?"

The issues section of github projects is used for technical issues.

**Comment by thomaspatzke** [comment]
As you can see, the last commit is three days old and if you check the branches you see I'm currently working on various new features and improvements. So no, it's definitely not dead. It's just a project with two maintainers, few further contributors, all with full-time jobs and the need for prioritizing support requests. And sorry, but stuff that is documented and can be easily figured out with the help function has a quite low priority.
