### ISSUE TITLE
Backends do not apply not-null filter

### ISSUE THREAD

**Issue by Karneades** [Neo23x0/sigma#410]
Backends do not apply not-null filter after conversion. Different backends (kibana, arcsight, ...) were tested. The filter gets removed and is missing in the final query. According to the [specs for special field values](https://github.com/Neo23x0/sigma/wiki/Specification#special-field-values) the use of the not-null value is allowed.

Example rule: [win_susp_svchost.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_svchost.yml).

```
    filter_null:
        ParentImage: null
```

After conversion, the query looks like the following for the rule above (missing null filter)

```
(Image="*\\svchost.exe" NOT ((ParentImage="*\\services.exe" OR ParentImage="*\\MsMpEng.exe" OR ParentImage="*\\Mrt.exe" OR ParentImage="*\\rpcnet.exe" OR ParentImage="")))
```

Expected behavior is that the not-null filter is added to the query e.g. for Splunk using `ParentImage=*`  to ensure that parent image is not null.

In the [Splunk backend](https://github.com/Neo23x0/sigma/blob/master/tools/sigma/backends/splunk.py) we find `notNullExpression = "%s=\"*\""`.

It's unclear whether the not-null filter should be implemented or if it's just missing in the backend.

**Comment by thomaspatzke** [comment]
My result is a bit different:

```
$ tools/sigmac -t es-qs -c winlogbeat rules/windows/process_creation/win_susp_svchost.yml
((winlog.event_data.Image.keyword:*\\svchost.exe AND (NOT (winlog.event_data.ParentImage.keyword:(*\\services.exe OR *\\MsMpEng.exe OR *\\Mrt.exe OR *\\rpcnet.exe)))) AND (NOT (NOT _exists_:winlog.event_data.ParentImage)))
```

Yes, the generated expression is a bit cumbersome, but it says that ParentImage should exist in the matched event, as required in the Sigma rule. Are you possibly using an old version of the Sigma converter? There were some bugs where the optimizer was too offensive in the past. Please try the most recent release or master branch.

**Comment by Karneades** [comment]
Thanks for your feedback. I see that the es-backend (and also the qradar) implements that not-null-node and therefore works as expected.

```
    def generateNotNULLValueNode(self, node):
        return {'exists': {'field': node.item}}

```

However, all the mentioned (and tested) backends from the first comment (Splunk, Kibana...) still not respect the not-null filter and I see they just not yet implemented that functionality (missing `generateNotNULLValueNode`  function). I think it would be good (and I will work on a PR) that backends will return an exception if a not-null value is used in a rule and the backend not yet implements that instead of silently transform the rule without that filter. Similar to if an operator is not yet implemented in a backend (`raise NotImplementedError("The 'near' aggregation operator is not yet implemented for this backend"`)).

**Comment by Karneades** [comment]
My bad, current version works as expected without the need of generateNotNULLValueNode :)
