### ISSUE TITLE
Move breaking changes to a dedicated changelog or issues

### ISSUE THREAD

**Issue by Karneades** [Neo23x0/sigma#414]
I would recommend using issues for discussion (and milestones for referencing a specific version) and a changelog (see [keep a changelog](https://keepachangelog.com/en/1.0.0/#how) and [semver](https://semver.org/)) to bring [breaking-changes](https://github.com/Neo23x0/sigma/blob/master/BREAKING_CHANGES.md) to attention. Monitoring a text file is bit inconvenient :)

**Comment by thomaspatzke** [comment]
Yes, this is definitely the plan. In the next months I will concentrate on code quality and plan a 1.0 release. From there a changelog will be maintained. Thanks for the links!

**Comment by thomaspatzke** [comment]
Added a change log down to 0.12 (for practicioning :wink:), following most of your suggestions. Thanks for providing these!
