### ISSUE TITLE
WDATP and PowerShell queries

### ISSUE THREAD

**Issue by import-au** [Neo23x0/sigma#423]
If this isn't the right place for this type of question, I apologize. I've been working a lot with WDATP recently and have been playing with the WDATP sigma backend. 

I've made a few changes on my local branch to support the [powershell malicious commandlets](https://raw.githubusercontent.com/Neo23x0/sigma/master/rules/windows/powershell/powershell_malicious_commandlets.yml) rule by adding
`        elif (self.category, self.product, self.service) == (None, "windows", "powershell"):
            self.table = "MiscEvents"
            self.orToken = ", `
to the generate() function and 
`        if self.table == "MiscEvents" and self.service == "powershell":
            return "%s | where tostring(extractjson('$.Command', AdditionalFields)) in~ " % self.table`
to the generateBefore() function.

You end up with a query something like:
`MiscEvents | where tostring(extractjson('$.Command', AdditionalFields)) in~ ("Invoke-DllInjection", ...<REMAINING KEYWORDS>)`

It's not the most efficient query but it gets us to at least an 80/20 mark. This also means this is the only PowerShell ATP rule that works b/c it relies on the name of the Cmdlet being ran, which is sort of parsed by ATP, whereas most of the other PowerShell Sigma rules rely on parameters (not cleanly parsed that I've seen).

Another way to approach this would be to create a second rule specific to ATP and then get more granular with the rule with something like:

`  selection1:
    EventType:
      - PowerShellCommand
  selection2:
    keywords:
      - <List of Cmdlets>
  condition: selection1 and selection2`

This offers more control at the expense of needing Sigma rules specific to ATP, or modifications to the other backends to handle or ignore ATP specific fieldMappings.

Looking for your opinions on how you think WDATP rules should be handled in the existing framework.

**Comment by thomaspatzke** [comment]
Hi! Can you provide this as pull request? I would like to integrate it into the Sigma converter. I prefer less efficient queries instead of backend specific rules. The latter stands in contrast to the core idea of Sigma of being query language agnostic.

**Comment by import-au** [comment]
Sure, I can. The fix I added would only allow [this rule file](https://raw.githubusercontent.com/Neo23x0/sigma/master/rules/windows/powershell/powershell_malicious_commandlets.yml) to work. Something [like this ](https://raw.githubusercontent.com/Neo23x0/sigma/master/rules/windows/powershell/powershell_malicious_keywords.yml)would not work. 

Without there being something to key off to note whether to look in the parameters vs Command, it would generate an incorrect ATP rule for the Malicious Keywords rule.

**Comment by thomaspatzke** [comment]
Thanks for the PR, just merged it!
