### ISSUE TITLE
sumologic.yml Clarification

### ISSUE THREAD

**Issue by sonius575** [Neo23x0/sigma#426]
Within the Sumologic.yaml notes:

Sumulogic mapping depends on customer configuration. Adapt to your context!
typically rule on _sourceCategory, _index or Field Extraction Rules (FER)
supposing existing FER for service, EventChannel, EventIDSumologic.

Can you clarify how the following values correlate with Sumo _sourceCategory, _index, etc...

logsources:
  linux:
    product: linux
    index: LINUX
  linux-sshd:
    product: linux
    service: sshd
    index: LINUX

I assume "Product" is just an identifier; but is "index" where I would add metadata info (_index, _source, _sourceCategory, etc...)? Also, "service" is just an identifier for the Sigma backend to identify what kind of Linux logs, for ex, we are dealing with?

Thanks for your help. I will be happy to contribute code once I figure this initial config out.

**Comment by juju4** [comment]
Hello @sonius575 

if you look at https://github.com/Neo23x0/sigma/blob/master/tools/config/sumologic.yml or similar configs
* product, category, service are fields as used in sigma rules
* index is the value expected in whatever backend index, which is _index for sumologic

Sumologic has many other fields like _sourceCategory, _sourceHost, _view, _collector. for now, those are not mapped in sigma rules, maybe a generic prefix rule would be interesting
Can see some on https://help.sumologic.com/Beta/Fields

Please note there is a related PR pending merge (390) which add mapping for most existing rules (https://github.com/Neo23x0/sigma/pull/390/files#diff-bf1a57f3b76f50abe912f0dd90474bb9R8)

**Comment by blaise-sumo** [comment]
Hi @juju4 , I'm looking forward to PR 390 and it seems like @thomaspatzke is looking at it now. BTW, if you are on the Sumo Dojo slack group, go ahead and connect with me. A few of the guys here are eager to help out, particularly with sigma2sumo.py.

**Comment by juju4** [comment]
Thanks @blaise-sumo. Will definitively try to reach out but on the move for few weeks so availability will vary.

**Comment by thomaspatzke** [comment]
This was fixed with #390, correct?
