### ISSUE TITLE
option to disable use .keyword for ES backends

### ISSUE THREAD

**Issue by neu5ron** [Neo23x0/sigma#431]
Elasticsearch default indexing type for strings will be keyword and the subfield will be were the analyzed text is stored (.text). Previously the subfield was .keyword and default field was text.
SIGMA default for rules with * in them is to use keyword field, right now users don't have a "good"/programmatic way to specify in a config, that allows them to override this and therefore NOT use ".keyword". A workaround temporarily (as you mentioned) is use sigmac option of keyword_blacklist= with a wildcard.

here is some reference code for you, but you probably know exactly what to do ;)
https://github.com/Neo23x0/sigma/blob/e1b1db8cca969837de9b507bc687bb551b53d3df/tools/sigma/backends/elasticsearch.py#L54

Per discussion offline opening this up as a reminder.

**Comment by neu5ron** [comment]
tested the temporary workaround using the wildcard on all of HELK with the new mapping of default field as keyword == works fine :) and rules fire as expected

**Comment by thomaspatzke** [comment]
Implemented this and fixed a small bug in wildcard matching.
