### ISSUE TITLE
Data dictionaries for fields

### ISSUE THREAD

**Issue by apbarros** [Neo23x0/sigma#46]
Hi, I wonder if anyone considered creating some official data dictionaries for some fields. The log source fields, for example. When the number of community created starts growing we'll see some challenges like rules referring to "Windows", "Microsoft Windows", "MS Windows", "windows-snare", etc. A place to get official dictionaries for fields like that would make it far easier to develop converters to proprietary formats.

I don't know much about YAML, so not sure about what are most appropriate ways to address this challenge. Do they do anything similar for YARA?

**Comment by 59e5aaf4** [comment]
The specification only has https://github.com/Neo23x0/sigma/wiki/Fields:-Processes , we'll need (in our case), the same variety of fields as were available in OpenIOC, e.g. as usable on https://www.iocbucket.com/openioceditor , see also https://github.com/fireeye/iocs/blob/master/APT3/62f65dae-9475-44b0-a9eb-c1baebbd9885.ioc .

That's mostly windows fields, but there are some generic (just like `processes`) categories that could benefit to the Sigma specification, like `network`, `registry`, `fileWrite`, etc.
