### ISSUE TITLE
elastalert - sigma_win_cmdkey_recon.yml (line break issue)

### ISSUE THREAD

**Issue by PurpleV0id** [Neo23x0/sigma#460]
Hi,

Sorry for creating another issue.  This rule converted to Elastalert:
      query: (event_id:"1" AND process_path.keyword:*\\cmdkey.exe AND process_command_line.keyword:*\
        \/list\ *)
However the line break seems to break this rule.  Removing the line break and \ so that it equals resolves the issue:

 query: (event_id:"1" AND process_path.keyword:*\\cmdkey.exe AND process_command_line.keyword:* \/list\ *)

or removing the wildcards and .keyword for process_command_line and resolves the issue as well. I will try and find some more examples and report back if i do. 

Thanks
Phil

**Comment by thomaspatzke** [comment]
Hi! Just fixed this issue by removal of the line breaks. Please try again.
