### ISSUE TITLE
Syntax issues exporting rules to elastalert format

### ISSUE THREAD

**Issue by flagod** [Neo23x0/sigma#463]
Hi, we're trying to convert some of the Sigma rules for elastalert and found some issues:
We're using wazuh as a hids, and our logs are generated by wazuh. As such, some of the fields do not match (eg CommandLine in wazuh's windows parser is called "data.EventChannel.EventData.CommandLine"). This can be fixed with a simple sed script, but do you have any plans to integrate with wazuh in the future?

The second and most serious question is that we have some syntax issues when we convert the alerts to elastalert format. For example, in the rule MsiExec-Web-Install_0, after the convertion we get the following rule: CommandLine:(*\ msiexec*\:\\\/\\\/*). This regex however, wont match unless you escape it correctly. 

Modifying it like this, we get the proper results:

CommandLine:(*msiexec*\:\/\/*)

We're using kibana Version: 6.5.4. After converting all of the sigma's rules to elastalert format we found that most didn't work due to syntax issues. Is there something we're doing wrong or does this feature need some more work?

Thanks!

**Comment by neu5ron** [comment]
just a comment on the wazuh conversion, I would ask the developers of that to provide a conversion file (taxonomy) similar to how HELK has one - as shown here (which was contributed or maintained by the HELK creator):
https://github.com/Neo23x0/sigma/blob/master/tools/config/helk.yml

**Comment by thomaspatzke** [comment]
> As such, some of the fields do not match (eg CommandLine in wazuh's windows parser is called "data.EventChannel.EventData.CommandLine"). This can be fixed with a simple sed script, but do you have any plans to integrate with wazuh in the future?

Replacing field names in Sigma rules is not the intended way for the usage of Sigma. Use [a configuration for your environment](https://github.com/Neo23x0/sigma/wiki/Converter-Tool-Sigmac#configuration-file) and invoke the Sigma converter with this configuration (`-c conf`). There are already [many](https://github.com/Neo23x0/sigma/tree/master/tools/config) configurations. I think the one for [Winlogbeat}(https://github.com/Neo23x0/sigma/blob/master/tools/config/winlogbeat.yml) would be the closest to what you want to reach. Unfortunately, configurations are not capable to express something like *prefix all field names except some with x*, but the *fieldlist* backend of the converter will give you a list of all field names. This command line does it for all rules in the open source repository: `tools/sigmac -t fieldlist -r rules`

> do you have any plans to integrate with wazuh in the future?

Yes, we're looking forward to your pull request :wink: It might be possible that I will have contact with Wazuh in the next months, but that's not sure. And until I don't get in touch with it it's unlikely that I will create a config for it, there's too much other stuff in Sigma that has to be done. In these cases we rely on contributors.

Regarding your other issue: can you give me the exact command line you use? I tried some conversions, but get always other results.

**Comment by goldarai** [comment]
Hi Thomas,

We are going to follow your recommendation about invoking the Sigma converter with a configuration for our environment. 

Regarding the other issue, we use the following command line to perform the tests: 
msiexec   /q /i http://127.0.01/tmp/cmd.png

Regards.

**Comment by goldarai** [comment]
To convert the "process creation" sigma rules into elastalert rules we use the following command:
python3 sigmac -t elastalert -r  /home/user/sigma/rules/windows/process_creation   -c /home/user/elastalert/elastalert.yml

**Comment by goldarai** [comment]
Hi guys, is there anything new about this issue? Thanks.

**Comment by thomaspatzke** [comment]
Hi! I will look into this next week!

**Comment by thomaspatzke** [comment]
Fixed this by removal of the escping in the rule, as it was unnecessary:

```
$ tools/sigmac -t es-qs -c winlogbeat rules/windows/process_creation/win_susp_msiexec_web_install.yml
winlog.event_data.CommandLine.keyword:(*\ msiexec*\:\/\/*)
```

**Comment by thomaspatzke** [comment]
Please test and reopen if required.

**Comment by goldarai** [comment]
Hi @thomaspatzke 

We've tested and and this keeps failing.

- ElasticSearch request 
GET /_search
{
    "query": {
        "query_string" : {
            "query" : "data.win.eventdata.commandLine:(*\ msiexec*\:\/\/*)"
        }
    }
}

- Output
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Unrecognized character escape ' ' (code 32)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@5632e40e; line: 4, column: 59]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Unrecognized character escape ' ' (code 32)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@5632e40e; line: 4, column: 59]"
  },
  "status": 500
}
