### ISSUE TITLE
I need Help

### ISSUE THREAD

**Issue by borbelyau** [Neo23x0/sigma#51]
Hy guys!
How are you?
I have some questions about the system... sorry for my "inconvinient question"

First... How I integrate this solution with Ossec? 
Second... This solution have any agent (on client side?)?

Tks guys!

**Comment by thomaspatzke** [comment]
> First... How I integrate this solution with Ossec?

You (or someone else) could write a sigmac backend for OSSEC rules for some automation. I think this is an interesting idea and documented it as issue #52.

> Second... This solution have any agent (on client side?)?

No and it's currently not planned. Sigma doesn't aims to be a SIEM or a IDS.
