### ISSUE TITLE
How to use the blacklist option?

### ISSUE THREAD

**Issue by AHooijdonk** [Neo23x0/sigma#510]
Hello,

I'm sorry but I'm at a loss how to use the blacklist option. For as far as I understand you can use it to tell sigmac to NOT add the .keyword field extension which it adds when you use a wildcard search. Winlogbeat 4.7.1 and it's template does not create .keyword fields for as far as I've been able to figure out so all rules containing wildcard searches fail because sigmac adds the .keyword field.
I can of coarse edit the search query, but why do manual labor when you've created such a great tool :) 
Tnx!

**Comment by thomaspatzke** [comment]
It's possible to provide wildcards to the blacklist. The option `-Okeyword_blacklist=*`does exactly what you want.
