### ISSUE TITLE
Add UUIDs for all rules

### ISSUE THREAD

**Issue by thomaspatzke** [Neo23x0/sigma#514]
Each rule should contain an *id* attribute with a randomly generated UUID according to the [Sigma identifier specification](https://github.com/Neo23x0/sigma/wiki/Specification#rule-identification).

**Comment by 59e5aaf4** [comment]
What about using UUIDv1, so that it embeds both a timestamp and a node ID ?

**Comment by thomaspatzke** [comment]
I don't think this is necessary, because time is already contained in versioning and some people would disregard embedding identification information in the UUID.

**Comment by thomaspatzke** [comment]
Implemented.
