### ISSUE TITLE
add new Value Modifier — endwith

### ISSUE THREAD

**Issue by yugoslavskiy** [Neo23x0/sigma#515]
There are plenty of examples (specifically, with process names) where we need "endwith" modifier instead of `contains`, which is great for its purpose but doesn't solve the issue. 

Here is an example:

```
NewProcessName: '*\reg.exe'
```

In the case with a new value modifier, we would just add:

```
NewProcessName|endwith: '\reg.exe'
```

And (in case of `es-qs`) would receive something like `"\\reg.exe"` in the query.

**Comment by thomaspatzke** [comment]
Implementing it with slightly modified naming, `endswith` to keep consistence with `contains` and freedom with Python devs :wink: Also added `startswith´ for completeness. You'll find it in the master branch now.
