### ISSUE TITLE
apt_babyshark.yml

### ISSUE THREAD

**Issue by zappeee** [Neo23x0/sigma#545]
When looking at the reference, "powershell.exe mshta.exe http" doesn't seem to be command line, instead it's a registry value.

```
        CommandLine:
            - reg query "HKEY_CURRENT_USER\Software\Microsoft\Terminal Server Client\Default"
            - powershell.exe mshta.exe http*
            - cmd.exe /c taskkill /im cmd.exe
```

**Comment by Neo23x0** [comment]
A registry value that gets executed every time the command prompt is started. 
https://devblogs.microsoft.com/oldnewthing/20071121-00/?p=24433
