### ISSUE TITLE
apt_elise.yml - Reference link not working

### ISSUE THREAD

**Issue by zappeee** [Neo23x0/sigma#546]
https://community.rsa.com/community/products/netwitness/blog/2018/02/13/lotus-blossom-continues-asean-targeting 

seems to be the new link

**Comment by Neo23x0** [comment]
Thanks. 

You could also try to: 
1. navigate to the rule in devel or master branch
2. click edit 
3. save changes
4. create pull request

**Comment by zappeee** [comment]
Thanks, haven't done that before.
But I'll give it a go in the future.
