### ISSUE TITLE
Packaging and distribution via PyPI

### ISSUE THREAD

**Issue by tomchop** [Neo23x0/sigma#59]
Thanks a lot for the contribution you're making with Sigma, I think it will solve problems for lots of people!

I am trying to integrate Sigma into Yeti (rule storage, validation, and exporting) and I was wondering if there was a way to easily parse a given rule (only for validation purposes). The code I have today is:

```
yaml_stream = cStringIO.StringIO(self.yaml)   # self.yaml is the string representation of the yaml rule
sigmaconfig = SigmaConfiguration()

try:
    SigmaCollectionParser(yaml_stream, sigmaconfig, None)
except (yaml.parser.ParserError, yaml.scanner.ScannerError) as e:
    raise IndicatorValidationError("YAML parsing error: {}".format(e))
except (SigmaParseError, SigmaCollectionParseError) as e:
    raise IndicatorValidationError("Sigma parsing error: {}".format(e))
```

The problem I have is using sigma (SigmaCollectionParser, etc.) from another app is a bit tricky since I haven't found any `setup.py` or pypy repo. Is there a cleaner way to "install" sigma besides cloning the repo and manually copying files?

Are there any plans to create an API for sigma so that other tools can interact with it?

Thanks!

**Comment by thomaspatzke** [comment]
Hi! Packaging and providing it via PyPI is planned.

**Comment by thomaspatzke** [comment]
It's now available on PyPI:
```
# pip3 install sigmatools
```
