### ISSUE TITLE
Can't pull the project

### ISSUE THREAD

**Issue by hyperbaba** [Neo23x0/sigma#612]
I am trying to pull the project and the error i see for days now is : 

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by Neo23x0** [comment]
https://lmgtfy.com/?q=%22Pulling+is+not+possible+because+you+have+unmerged+files.%22
