### ISSUE TITLE
requirements for the tool in README.md

### ISSUE THREAD

**Issue by wlet** [Neo23x0/sigma#62]
Hi,

just checked out the project on a RHEL system. Now I'm in the process of figuring out what packages and even what python version is recommended/required. This is a bit bothersome

Would be really helpful if you could make that information easily available. (Not specifically for RHEL, but generally). I would issue a pull request but I still haven't make it work yet.

cheers

wlet

**Comment by thomaspatzke** [comment]
The Sigma tools in tools/ run fine with Python 3.5 and the current version of PyYAML. In case you want to run the test suite, you additionally need coverage and yamllint.

Added requirements.txt and requirements-devel.txt to the main repository.
