### ISSUE TITLE
Discrepancies between specs and sample rules

### ISSUE THREAD

**Issue by SherifEldeeb** [Neo23x0/sigma#63]
Schema in the specs defines "reference" and "falsepositives" to be `str`; yet sometimes they're `str`, sometimes they are `list` in the sample rules.

If I may suggest going with "list" and update the rules accordingly, changing single `str`s to a `list` with one item for the sake of consistency (I'd gladly update all the rules and submit a PR), or if it will be decided that they could be either a `str` or `list`,  then update the specs.

**Comment by thomaspatzke** [comment]
Thanks for pointing this out! This should be a list of strings, as alternatives are not allowed in the Schema definition. Already fixed that in the specification. PR with the fixed rules would be nice!

**Comment by SherifEldeeb** [comment]
Thanks for updating "falsepositives" in the schema, but I believe "reference" is still defined as `str` ... I know it's too late to call it "references", but I guess it should be a list as well nevertheless.

re:PR: will do when I have time (hopefully < a week)

**Comment by thomaspatzke** [comment]
Yes - just renamed it to *references* and made a list from it.

Ok, that's fine, looking forward to your PR :)

**Comment by SherifEldeeb** [comment]
should be addressed by https://github.com/Neo23x0/sigma/pull/64
