### ISSUE TITLE
[Elastalert] Escaping the character 'u'

### ISSUE THREAD

**Issue by HarishHary** [Neo23x0/sigma#662]
Hello sigma team.

I recently bumped into the following issue:

* With a following field value string:
`ProcessName: 'C:\\\\Users\\\\Microsoft Security Client\\\\MsMpEng.exe'`
* It generates the following string for the query:
`ProcessName:("C\:\\\\Users\\\\Microsoft\ Security\ Client\\\\MsMpEng.exe")`

* And with the following field value string:
`ProcessName: 'C:\\\\users\\\\Microsoft Security Client\\\\MsMpEng.exe'`
* It generates the following string for the query:
`ProcessName:("C\:\\\\\users\\\\Microsoft\ Security\ Client\\\\MsMpEng.exe")`

As you can see the smaller case `\us` gets considered as `unicode` character.
Not sure if it should be the case ? Can you confirm if this is a correct behavior ?

Best regards,

**Comment by neu5ron** [comment]
@thomaspatzke I think we can fix this ["problematic code"](https://github.com/Neo23x0/sigma/blob/cbf0f4393412c51e00b07430e16daddd310d7b32/tools/sigma/backends/elasticsearch.py#L83) by removing the escape of the `u` character.
but before I submit a PR - was there any gotcha, for when you implemented this?

**Comment by neu5ron** [comment]
PR submitted for this fix in #659

**Comment by HarishHary** [comment]
Hello, @neu5ron 

I tried to apply your fix by just removing the letter `u`. It somehow fixes the following issue: https://github.com/Neo23x0/sigma/issues/672

Can you explain to me what this `witchy`-regex does ?
And how just removing the letter `u` works ?

Best regards,

**Comment by thomaspatzke** [comment]
The escaping of \u is required in cases where this character sequence appears in Sigma rules. In Elastic it has a special meaning and causes errors while parsing of queries. Simply removing it will reintroduce an old bug I've fixed by adding this escaping.

**Comment by thomaspatzke** [comment]
To fix your issue: single backslashes should be sufficient in the rule.

**Comment by HarishHary** [comment]
@thomaspatzke You start from the assumption that the log only have a single backslash. Let's say I have 2 backslashes on the log. What should I write ? Can you give an example ? And can you add those special/corner cases examples in the documentation ?

**Comment by thomaspatzke** [comment]
It is also allowed (and required to catch some corner cases) to escape backslashes. Therefore `\\` is not sufficient to express this. `\\\` should work as well as `\\\\`, but I would prefer to use four backslashes to avoid mixed notation in the same value.

**Comment by thomaspatzke** [comment]
Documented how to backslash correctly in the [wiki](https://github.com/Neo23x0/sigma/wiki/Rule-Creation-Guide#backslashes).

**Comment by sarkortrantor** [comment]
Hello I'm confused about the backslashes too, (I read https://github.com/Neo23x0/sigma/wiki/Rule-Creation-Guide#backslashes)
as a concrete example:
how does sigma parser handle those, what are the precedence/tokenisation/decoding rules ?: 
- ```\\``` : "It is also allowed (and required to catch some corner cases) to escape backslashes" => result ```\```
- ```\\\\*``` : is it 
    - ```\\``` -> ```\``` then ```\\*``` -> ```\*``` ("plain backslash followed by wildcard") => result  ```\\*``` (two backslashes followed by wildcard) or 
    - ```\``` -> ```\``` 'then ```\\\*``` (plain backslash followed by a plain *) => result ```\\*``` (two backslashes followed by  a plain *)
- ```\\\\users``` why is this not interpreted as ```\\``` -> ```\``` then ```\\``` -> ```\``` then ```u``` ? 

- also if the rule of thumb is: don't escape single backslashes unless you are forced ("required to catch some corner cases") when are we forced ? (to remain consistent with the two plain backslashes cases (```\\\\``` -> ```\\```) I would prefer to use ```\\``` -> ```\``` but need to know the corner cases..)

also I'm not sure to understand the rationale behind having multiple functions for a single char,

thank you, best regards,
