### ISSUE TITLE
extend schema to include mitre att&ck tactics/techniques

### ISSUE THREAD

**Issue by neelsenc** [Neo23x0/sigma#67]
the ruleset provided here is amazing and a invaluable resource for identifying new detections that need implemented in our environment.  we have been mapping all of our detections to MITRE's ATT&CK matrix and it would be awesome if the sigma rule definitions already had this mapping.

thoughts?

**Comment by thomaspatzke** [comment]
We had the idea of a generic list of tags which could also be used for ATT&CK mapping. What do you think about this idea? Would this be sufficient?

**Comment by avuko** [comment]
I would love to help with this effort, whichever way it is eventually implemented. Please let me know if you need extra hands for the grunt work (or otherwise).

**Comment by jmallette** [comment]
Generic tags could work for this, we just need to reuse the same pattern to identify them all. It's also much more adaptable to other potential uses as well.

**Comment by thomaspatzke** [comment]
[Done](https://github.com/Neo23x0/sigma/wiki/Tags)
