### ISSUE TITLE
[Backend][MDATP] renaming and schema changes

### ISSUE THREAD

**Issue by tileo** [Neo23x0/sigma#675]
WDATP was renamed to MDATP (Microsoft Defender ATP).
MDATP also had schema changes recently: https://techcommunity.microsoft.com/t5/microsoft-defender-atp/advanced-hunting-data-schema-changes/ba-p/1043914

Pull request to fix these: https://github.com/Neo23x0/sigma/pull/658

**Comment by thomaspatzke** [comment]
PR was merged, thanks!
