### ISSUE TITLE
Disable automatic windows defragementation rule

### ISSUE THREAD

**Issue by sfakiana** [Neo23x0/sigma#70]
It would be nice to create a sigma rule to monitor disabling of windows automatic defragmentation
https://securelist.com/apt-slingshot/84312/

**Comment by Neo23x0** [comment]
Done 

https://github.com/Neo23x0/sigma/blob/master/rules/apt/apt_slingshot.yml

**Comment by sfakiana** [comment]
!!! That was really quick Florian :) 
what about the scheduled task via Sysmon EventID1?
schtasks /Delete /TN "\Microsoft\Windows\Defrag\ScheduledDefrag" /F
https://superuser.com/questions/1210453/windows-10-disable-automatic-defragmentation

**Comment by Neo23x0** [comment]
Check https://github.com/Neo23x0/sigma/commit/74c2f91a7d1fd52f3f688852ed87580cbd28712e?diff=split

**Comment by sfakiana** [comment]
good stuff Florian! I think it's fine. Many thanks!

**Comment by Neo23x0** [comment]
👍
