### ISSUE TITLE
Bug in function generateMapItemTypedNode in file qradar.py

### ISSUE THREAD

**Issue by ayatsyny** [Neo23x0/sigma#702]
in file https://github.com/Neo23x0/sigma/blob/master/tools/sigma/backends/qradar.py#L113 
have error in line string. Value **_node_** don't present in args function  **_generateMapItemTypedNode_**

 ```
NotImplementedError("Type modifier '{}' is not supported by backend".format(node.identifier))
```

**Comment by thomaspatzke** [comment]
Thanks, fixed!
