### ISSUE TITLE
Differentiate error and success response

### ISSUE THREAD

**Issue by sarveshvish971996** [Neo23x0/sigma#713]
How can i differentiate between success response and error response of sigma command. I was trying to automate the sigma execution.

**Comment by thomaspatzke** [comment]
sigmac returns exit codes. Could you please specify where a wrong exit code is returned?

Furthermore, you can use the converter code also as library. See the sigmac code for reference.

**Comment by sarveshvish971996** [comment]
is there error code for yaml validation if yaml file is syntatically incorrect

**Comment by thomaspatzke** [comment]
Yes, it's 3, [see here](https://github.com/Neo23x0/sigma/blob/514bd8657bdd2a5d96d13a7b22b42e08cce6ba33/tools/sigmac#L42).
