### ISSUE TITLE
[Feature Request] Convert existing SIEM queries to Sigma notation

### ISSUE THREAD

**Issue by dmoore44** [Neo23x0/sigma#72]
It would be helpful if there were a utility that allowed us to convert existing query catalogs in Splunk/ELK/etc... to Sigma notation so that a uniform documentation standard can be built and stored in a git repo.

**Comment by thomaspatzke** [comment]
I think that's hard to solve, as we have to parse each query language and map as much features as possible to Sigma.

**Comment by debernal** [comment]
It would be great to add, at least only for ELK :)

**Comment by JohnOmernik** [comment]
So https://uncoder.io/ is doing this (or something like this) under the hood. Probably using Sigma... This would be much more useful to the community in the form of an enhancement to Sigma, or a standalone Open Source library. (Who is going to put their sensitive Security queries in someone else's website? ) (Also, it doesn't seem to work).   Any more thoughts on the ability to do the Siem searches -> Sigma?
