### ISSUE TITLE
Values of 'source' for windows-application

### ISSUE THREAD

**Issue by zaphodef** [Neo23x0/sigma#746]
Hi! I'm pretty new to sigma, so I may be wrong but it seems to me the correct value for [the 'source' field in `win_susp_backup_delete`](https://github.com/Neo23x0/sigma/blob/82cae6d63c9c2f6d3e86c57e11497d86279b9f95/rules/windows/builtin/win_susp_backup_delete.yml#L19) is "Microsoft-Windows-Backup", "Backup" being only the displayed value (not the value exported). If so, I can go ahead and make a PR, but I may be missing something.

**Comment by Neo23x0** [comment]
Yes, please PR
