### ISSUE TITLE
Filter of private address includes public IP address.

### ISSUE THREAD

**Issue by initiate6** [Neo23x0/sigma#75]
https://github.com/Neo23x0/sigma/blob/39625208483cc2090c78aa6a10acf13e30efdbdb/rules/windows/sysmon/sysmon_rundll32_net_connections.yml#L19

https://en.wikipedia.org/wiki/Private_network
There are public IP address in this range 172.*. It should be 
^172\.1[6-9]\.
^172\.2[0-9]\.
^172\.3[0-1]\.
And missing loopback not sure if it's important. 
^127\.0\.0\.1

Minor issue with line piblic should be public

**Comment by herrBez** [comment]
I think that this issue seems to be resolved [in the current version](https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_rundll32_net_connections.yml)

**Comment by itpropaul** [comment]
Can someone share a rule that uses IP ranges? I haven't come across any yet.

**Comment by frack113** [comment]
A example [sysmon_rundll32_net_connections.yml](https://github.com/SigmaHQ/sigma/blob/0109a5f013191961cee7db493fe7772bdc8826c0/rules/windows/network_connection/sysmon_rundll32_net_connections.yml)
in the near futur [pySigma](https://github.com/SigmaHQ/pySigma)

**Comment by itpropaul** [comment]
Right on, thanks @frack113. Based on the conversation, it seemed like this was already done but when I looked around I couldn't find any examples. 

I'm looking forward to the new version.
