### ISSUE TITLE
[Feature Request] - Add possibility to convert to Windows Defender ATP hunting queries

### ISSUE THREAD

**Issue by api0cradle** [Neo23x0/sigma#79]
Examples of queries can be found here:
https://github.com/Microsoft/WindowsDefenderATP-Hunting-Queries

Would be useful to use the Sigma signatures against this.

**Comment by thomaspatzke** [comment]
Was on my todo list and I just started to implement this ;)

**Comment by robomotic** [comment]
Excellent, I actually worked with Tomer on this project, if you need any help let me know.

**Comment by thomaspatzke** [comment]
First version implemented
