### ISSUE TITLE
Backends invalid syntax ?

### ISSUE THREAD

**Issue by kuronastu** [Neo23x0/sigma#87]
Hi,

When I use the sigmac tool, I've an error syntax:

```
Traceback (most recent call last):
  File "tools/sigmac", line 27, in <module>
    import sigma.backends as backends
  File "sigma-master/tools/sigma/backends.py", line 681
    **min_doc_count
     ^
SyntaxError: invalid syntax

```

Host is debian os, and I installed sigma with pip3.

**Comment by thomaspatzke** [comment]
The Sigma converter at least requires Python 3.5 or newer. This is the case for the current Debain stable release. Older versions cause the above error message.
