### ISSUE TITLE
sysmon_uac_bypass_eventvwr.yml broken by move to sysmon registry_event category

### ISSUE THREAD

**Issue by rtkbkish** [Neo23x0/sigma#888]
Compare:
https://github.com/Neo23x0/sigma/blob/release-0.17.0/rules/windows/sysmon/sysmon_uac_bypass_eventvwr.yml

to 
https://github.com/Neo23x0/sigma/blob/master/rules/windows/registry_event/sysmon_uac_bypass_eventvwr.yml

The event-id 1 (process creation) subexpression will never be evaluated since the rule requires that event 12, 13 or 14.

**Comment by thomaspatzke** [comment]
Oh yes, that was wrong...thanks for fixing all the rules (again) :+1:
