### ISSUE TITLE
New network_connection category for sysmon conflates DNS and network connection.

### ISSUE THREAD

**Issue by rtkbkish** [Neo23x0/sigma#889]
Of the rules in the new "network_connection" path, all previously specified EventID 3, except for "sysmon_regsvr32_network_activity.yml". Most of the rules make no sense for DNS events. 

I think the "network_connection" category should only map to EventID 3, and for rules which also need to apply to DNS events, a separate rule be defined

**Comment by thomaspatzke** [comment]
Improved the fix and will merge it when CI passes. Thanks for your contribution!
