### ISSUE TITLE
windows/process_creation/win_powershell_suspicious_parameter_variation rule's values incorrect?

### ISSUE THREAD

**Issue by barvhaim** [Neo23x0/sigma#923]
For rule: `windows/process_creation/win_powershell_suspicious_parameter_variation.yml`, is `CommandLine` values should use `LIKE` asterisks wrapping? it looks like part of a string (even begin and ends with a whitespace), I mean, should it be for example `'* -windowstyle h *'` in oppose to `' -windowstyle h '`

**Comment by Neo23x0** [comment]
Yeah, that's a bug. I'll fix it.

**Comment by Neo23x0** [comment]
Fixed in https://github.com/Neo23x0/sigma/pull/925
