### ISSUE TITLE
[config][winlogbeat][bug] Add EventID to category process_creation

### ISSUE THREAD

**Issue by SanWieb** [Neo23x0/sigma#933]
All rules present in the category 'process_creation' have no EventID defined in the selection. This is logical because the eventid is always 1.

But when you convert the rule to es-dsl there is also no eventID. Let's take for example this rule: https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_svchost_no_cli.yml. It will be converted to:

`{"query": {"constant_score": {"filter": {"bool": {"must": [{"wildcard": {"data.win.system.eventID": "1"}}, {"bool": {"should": [{"bool": {"should": [{"wildcard": {"data.win.eventdata.commandLine": "*\\\\Service.exe i"}}, {"wildcard": {"data.win.eventdata.commandLine": "*\\\\Service.exe u"}}, {"wildcard": {"data.win.eventdata.commandLine": "*\\\\microsoft\\\\Taskbar\\\\autoit3.exe"}}, {"wildcard": {"data.win.eventdata.commandLine": "C:\\\\wsc.exe*"}}]}}, {"wildcard": {"data.win.eventdata.image": "*\\\\Windows\\\\Temp\\\\DB\\\\*.exe"}}, {"bool": {"must": [{"wildcard": {"data.win.eventdata.commandLine": "*\\\\nslookup.exe -q=TXT*"}}, {"wildcard": {"data.win.eventdata.parentImage": "*\\\\Autoit*"}}]}}]}}]}}}}}`

As a result, this rule will also match incorrectly on a registry event (e.g. eventID 11), which never contain a command line.

**To Solve:**
Add to the configuration of winlogbeat (and maybe others?) product `windows` with category `process_creation` and as condition `eventID : '1'`

**Comment by Neo23x0** [comment]
What was you full command line? Which source config did you apply? 

Is it possible that we only have a config for Sysmon and Windows (native; 4688 only) to map the new `generic` categories to event IDs? 
@thomaspatzke @neu5ron 

No one noticed that before? 

![Screenshot 2020-07-16 at 13 17 50](https://user-images.githubusercontent.com/2851492/87665168-c7bf0e00-c766-11ea-9aee-2e74ad7b1019.png)

![Screenshot 2020-07-16 at 13 24 59](https://user-images.githubusercontent.com/2851492/87665793-c510e880-c767-11ea-842d-f9386d4ba562.png)

**Comment by thomaspatzke** [comment]
You have to chain configurations. First the one that maps generic log sources like process_creation to Sysmon events `-c sysmon` and then the one for your backends and environment.

**Comment by SanWieb** [comment]
Full command:
`python tools\sigmac -t es-dsl -c tools\config\winlogbeat.yml rules\windows\process_creation\win_susp_svchost_no_cli.yml`

So i used the config `winlogbeat.yml`, but i see now that it applies voor many more ( elk-defaultindex.yml, elk-defaultindex, filebeat.yml, elk-windows.yml ....).

In 6c35a7afa0331120c82f93d4748f0cf9153bc568 I added the `eventID` condition, but as you mentioned the generic templates, it would be better to first convert all sigma rules with generic/sysmon and thereafter convert it with a specific config.

Is this possible in one command?

**Comment by thomaspatzke** [comment]
By the way, your generated query already contains the matching on event id 1: 
> `{"query": {"constant_score": {"filter": {"bool": {"must": [{"wildcard": {"data.win.system.eventID": "1"}}, {"bool":

**Comment by SanWieb** [comment]
> By the way, your generated query already contains the matching on event id 1:
> 
> > `{"query": {"constant_score": {"filter": {"bool": {"must": [{"wildcard": {"data.win.system.eventID": "1"}}, {"bool":

You are right, my fault. Copied the wrong query (the one which I already solved by adding it to the configuration)

**Comment by thomaspatzke** [comment]
Yes, you just need to chain the configurations:

`sigmac ... -c sysmon -c winligbeat ...`
