### ISSUE TITLE
Duplicate tags on many rules

### ISSUE THREAD

**Issue by IPv777** [Neo23x0/sigma#951]
Hello,

![image](https://user-images.githubusercontent.com/19636346/88526308-13da4000-cffc-11ea-86f2-66a3caba9062.png)
On many rules I seen duplicate tags, maybe we could create a script to remove the duplicate and set it up with the CI/audit bots ?

**Comment by Neo23x0** [comment]
Fixing this with 
https://github.com/Neo23x0/sigma/pull/952
