### ISSUE TITLE
sigmac: crowdstrike "CommandLine" should use upper-case L

### ISSUE THREAD

**Issue by mrezqi** [Neo23x0/sigma#956]
As it said in the title, conversion result from sigma to crowdstrike is not working properly because the L in Commandline is in lower-case.

**Comment by thomaspatzke** [comment]
Did you've used the CrowdStrike configuration? [It contains](https://www.github.com/Neo23x0/sigma/tree/master/tools%2Fconfig%2Fcrowdstrike.yml) a mapping for the command line field. Try it with the parameter `-c crowdstrike` in the command line.
