### ISSUE TITLE
Field comparaison

### ISSUE THREAD

**Issue by HarishHary** [Neo23x0/sigma#962]
Hello,

Do you think there is a way to compare fields between them ?
Like if 2 fields are equal => do not trigger an alert for it.
I think this feature is backend agnostic and it's more useful to avoid false positive in some cases. 

Best regards,

Harish

**Comment by thomaspatzke** [comment]
Currently there's no way for this and it has low priority to implement because it's complex to implement, many backends aren't capable to do this and there are only very few use cases for this.
