### ISSUE TITLE
Sigma condition grammar

### ISSUE THREAD

**Issue by shellcromancer** [Neo23x0/sigma#972]
Has anyone written a grammar and Bison parser for the Sigma grammar from the [specification](https://github.com/Neo23x0/sigma/wiki/Specification#condition)?

I'm trying to implement a Golang parser and it would be helpful to make use the same rules as the current parser so standardizing with a grammar could help.

**Comment by thomaspatzke** [comment]
Here is the custom parser code including:

- [tokens](https://github.com/Neo23x0/sigma/blob/master/tools/sigma/parser/condition.py#L48)
- [condition parsing rules](https://github.com/Neo23x0/sigma/blob/d73447c111464f34e2bdd3973056c5b138e0a06b/tools/sigma/parser/condition.py#L484)
- [aggregation state machine](https://github.com/Neo23x0/sigma/blob/d73447c111464f34e2bdd3973056c5b138e0a06b/tools/sigma/parser/condition.py#L572)

No grammar yet, sorry. I'm currently working on a complete rewrite of the code including a lark-based parser with a grammar.
